//! status=pending
_root.fightStat = "Lullaby Lake?";
_root.areaSafe = false;
_root.areaUnderwater = false;
_root.areaSpawn = 3.5;
_root.areaSpawnReduce = 75;
_root.areaRareChance = 5;
_root.areaAllyChance = 2;
_root.areaDamagePct = 1;
_root.areaEpicChance = 1;
_root.areaEpicChance2 = 4;
_root.areaFairyPerformance = 0;
_root.areaFairyPower = false;
_root.challengeCompatible = true;
_root.challengeRewardMul = 2.25;
