//! status=pending
_root.fightStat = "Pokayman City EX";
_root.areaSafe = false;
_root.areaUnderwater = false;
_root.areaSpawn = 2.7;
_root.areaSpawnReduce = 75;
_root.areaRareChance = 10;
_root.areaAllyChance = 5;
_root.areaDamagePct = 1;
_root.areaEpicChance = 1;
_root.areaEpicChance2 = 4;
_root.challengeCompatible = true;
_root.challengeRewardMul = 3;
