//! status=pending
_root.fightStat = "Deadlands";
_root.areaSafe = false;
_root.areaUnderwater = false;
_root.areaSpawn = 2.5;
_root.areaSpawnReduce = 75;
_root.areaRareChance = 1.5;
_root.areaAllyChance = 15;
_root.areaDamagePct = 100;
_root.areaEpicChance = 0;
_root.areaEpicChance2 = 0.5;
_root.challengeCompatible = true;
_root.challengeRewardMul = 1.15;
