//! status=pending
_root.fightStat = "The Desert";
_root.areaSafe = false;
_root.areaUnderwater = false;
_root.areaSpawn = 2.4;
_root.areaSpawnReduce = 75;
_root.areaRareChance = 1.6;
_root.areaAllyChance = 10;
_root.areaDamagePct = 100;
_root.areaEpicChance = 0;
_root.areaEpicChance2 = 0.6;
_root.challengeCompatible = true;
_root.challengeRewardMul = 1.17;
