//! status=pending
_root.fightStat = "-Infinity: Prehistoric Area";
_root.areaSafe = false;
_root.areaUnderwater = false;
_root.areaSpawn = 2.2;
_root.areaSpawnReduce = 25;
_root.areaRareChance = 5;
_root.areaAllyChance = 1;
_root.areaDamagePct = 10;
_root.areaEpicChance = 0.1;
_root.areaEpicChance2 = 1;
_root.challengeCompatible = false;
