//! status=pending
_root.fightStat = "Ropeless Room";
_root.areaSafe = false;
_root.areaUnderwater = false;
_root.areaSpawn = 10;
_root.areaSpawnReduce = 0;
_root.areaRareChance = 1;
_root.areaAllyChance = 1;
_root.areaDamagePct = 100;
_root.areaEpicChance = 0;
_root.areaEpicChance2 = 0.1;
_root.challengeCompatible = false;
