//! status=pending
_root.fightStat = "Danger Zone";
_root.areaSafe = false;
_root.areaUnderwater = false;
_root.areaSpawn = 10;
_root.areaSpawnReduce = 0;
_root.areaRareChance = 0;
_root.areaAllyChance = 1;
_root.areaDamagePct = 8;
_root.areaEpicChance = 0;
_root.areaEpicChance2 = 0;
_root.labEnemy = 0;
_root.challengeCompatible = false;
