//! status=pending
_root.fightStat = "Treasure Room";
_root.areaSafe = false;
_root.areaUnderwater = false;
_root.areaSpawn = 99;
_root.areaSpawnReduce = 0;
_root.areaRareChance = 100;
_root.areaAllyChance = 1;
_root.areaDamagePct = 10;
_root.challengeCompatible = false;
_root.areaEpicChance = 50;
_root.areaEpicChance2 = 100;
