//! status=pending
_root.fightStat = "Foodlandistan";
_root.areaSafe = false;
_root.areaUnderwater = false;
_root.areaSpawn = 10;
_root.areaSpawnReduce = 25;
_root.areaRareChance = 100;
_root.areaAllyChance = 2.5;
_root.areaDamagePct = 0.1;
_root.areaEpicChance = 0;
_root.areaEpicChance2 = 100;
_root.challengeCompatible = false;
