//! status=pending
_root.fightStat = "Secret Entrance";
_root.areaSafe = true;
_root.areaUnderwater = false;
_root.areaSpawn = 10;
_root.areaSpawnReduce = 0;
_root.areaRareChance = 0;
_root.areaAllyChance = 0;
_root.areaDamagePct = 100;
_root.areaEpicChance = 0;
_root.areaEpicChance2 = 0;
_root.challengeCompatible = false;
