//! status=pending
_root.fightStat = "Fabled Forest?";
_root.areaSafe = false;
_root.areaUnderwater = false;
_root.areaSpawn = 3.3;
_root.areaSpawnReduce = 75;
_root.areaRareChance = 7;
_root.areaAllyChance = 2;
_root.areaDamagePct = 0.8;
_root.areaEpicChance = 1.4;
_root.areaEpicChance2 = 6;
_root.areaFairyPerformance = 0;
_root.areaFairyPower = false;
_root.challengeCompatible = true;
_root.challengeRewardMul = 2.75;
