//! status=pending
_root.fightStat = "Throne Room";
_root.areaSafe = false;
_root.areaUnderwater = false;
_root.areaSpawn = 3.3;
_root.areaSpawnReduce = 25;
_root.areaRareChance = 5;
_root.areaAllyChance = 1;
_root.areaDamagePct = 10;
_root.areaEpicChance = 0.7;
_root.areaEpicChance2 = 3;
_root.areaFairyPerformance = 0;
_root.areaFairyPower = false;
_root.challengeCompatible = true;
_root.challengeRewardMul = 2.5;
