//! status=pending
_root.fightStat = "Dark Portal";
_root.areaSafe = false;
_root.areaUnderwater = false;
_root.areaSpawn = 10;
_root.areaSpawnReduce = 25;
_root.areaRareChance = 5;
_root.areaAllyChance = 1;
_root.areaDamagePct = 100;
_root.areaFinalizerRank = 100;
_root.areaEpicChance = 0.4;
_root.areaEpicChance2 = 2;
_root.challengeCompatible = false;
