//! status=pending
_root.fightStat = "Night Forest";
_root.areaSafe = false;
_root.areaUnderwater = false;
_root.areaSpawn = 2.5;
_root.areaSpawnReduce = 75;
_root.areaRareChance = 1.3;
_root.areaAllyChance = 25;
_root.areaDamagePct = 100;
_root.areaEpicChance = 0;
_root.areaEpicChance2 = 0.3;
_root.challengeCompatible = true;
_root.challengeRewardMul = 1.13;
