//! status=pending
_root.fightStat = "Billygoat Bridge";
_root.areaSafe = false;
_root.areaUnderwater = false;
_root.areaSpawn = 3.7;
_root.areaSpawnReduce = 25;
_root.areaRareChance = 3.3;
_root.areaAllyChance = 1;
_root.areaDamagePct = 18;
_root.areaEpicChance = 0.3;
_root.areaEpicChance2 = 1.7;
_root.areaFairyPerformance = 0;
_root.areaFairyPower = false;
_root.challengeCompatible = true;
_root.challengeRewardMul = 1.6;
