//! status=pending
_root.fightStat = "Castle Grimm?";
_root.areaSafe = false;
_root.areaUnderwater = false;
_root.areaSpawn = 3.1;
_root.areaSpawnReduce = 75;
_root.areaRareChance = 9;
_root.areaAllyChance = 2;
_root.areaDamagePct = 0.6;
_root.areaEpicChance = 2;
_root.areaEpicChance2 = 10;
_root.areaFairyPerformance = 0;
_root.areaFairyPower = false;
_root.challengeCompatible = true;
_root.challengeRewardMul = 3.5;
