//! status=pending
_root.fightStat = "Pirate Ship";
_root.areaSafe = false;
_root.areaUnderwater = false;
_root.areaSpawn = 2;
_root.areaSpawnReduce = 75;
_root.areaRareChance = 2;
_root.areaAllyChance = 5;
_root.areaDamagePct = 100;
_root.areaEpicChance = 0.2;
_root.areaEpicChance2 = 1;
_root.challengeCompatible = true;
_root.challengeRewardMul = 1.5;
