//! status=pending
_root.fightStat = "2011: Dragon Cave";
_root.areaSafe = false;
_root.areaUnderwater = false;
_root.areaSpawn = 7.5;
_root.areaSpawnReduce = 0;
_root.areaRareChance = 1;
_root.areaAllyChance = 1;
_root.areaDamagePct = 1;
_root.areaEpicChance = 1;
_root.areaEpicChance2 = 2;
_root.challengeCompatible = false;
