//! status=pending
_root.fightStat = "Water Room";
_root.areaSafe = false;
_root.areaUnderwater = true;
_root.areaSpawn = 99;
_root.areaSpawnReduce = 0;
_root.areaRareChance = 100;
_root.areaAllyChance = 1;
_root.areaDamagePct = 5;
_root.challengeCompatible = false;
_root.areaEpicChance = 10;
_root.areaEpicChance2 = 100;
