//! status=pending
pName = _root.save["tech" + _root.selectedLight + "Program"];
s1 = _root.save["tech" + _root.selectedLight + "StringA"];
s2 = _root.save["tech" + _root.selectedLight + "StringB"];
s3 = _root.save["tech" + _root.selectedLight + "NumberA"];
s4 = _root.save["tech" + _root.selectedLight + "NumberB"];
s5 = _root.save["tech" + _root.selectedLight + "NumberC"];
b1 = _root.save["tech" + _root.selectedLight + "Array"][1];
b2 = _root.save["tech" + _root.selectedLight + "Array"][2];
b3 = _root.save["tech" + _root.selectedLight + "Array"][3];
b4 = _root.save["tech" + _root.selectedLight + "Array"][4];
b5 = _root.save["tech" + _root.selectedLight + "Array"][5];
b6 = _root.save["tech" + _root.selectedLight + "Array"][6];
b7 = _root.save["tech" + _root.selectedLight + "Array"][7];
b8 = _root.save["tech" + _root.selectedLight + "Array"][8];
b9 = _root.save["tech" + _root.selectedLight + "Array"][9];
b10 = _root.save["tech" + _root.selectedLight + "Array"][10];
