//! status=pending
_root.fightStat = "Billygoat Bridge?";
_root.areaSafe = false;
_root.areaUnderwater = false;
_root.areaSpawn = 3.4;
_root.areaSpawnReduce = 75;
_root.areaRareChance = 6;
_root.areaAllyChance = 2;
_root.areaDamagePct = 0.9;
_root.areaEpicChance = 1.2;
_root.areaEpicChance2 = 5;
_root.areaFairyPerformance = 0;
_root.areaFairyPower = false;
_root.challengeCompatible = true;
_root.challengeRewardMul = 2.5;
