//! status=pending
_root.fightStat = "Smiley Island";
_root.areaSafe = false;
_root.areaUnderwater = false;
_root.areaSpawn = 2.5;
_root.areaSpawnReduce = 50;
_root.areaRareChance = 0.5;
_root.areaAllyChance = 5;
_root.areaDamagePct = 100;
_root.challengeCompatible = true;
_root.areaEpicChance = 0.2;
_root.areaEpicChance2 = 1;
_root.challengeRewardMul = 1.6;
