//! status=pending
_root.fightStat = "9001: Secret Lab";
_root.areaSafe = false;
_root.areaUnderwater = true;
_root.areaSpawn = 10;
_root.areaSpawnReduce = 25;
_root.areaRareChance = 100;
_root.areaAllyChance = 1;
_root.areaDamagePct = 0;
_root.areaEpicChance = 10;
_root.areaEpicChance2 = 50;
_root.challengeCompatible = false;
