//! status=pending
_root.fightStat = "Advanced Training Zone";
_root.areaSafe = false;
_root.areaUnderwater = false;
_root.areaSpawn = 2.5;
_root.areaSpawnReduce = 75;
_root.areaRareChance = 1.1;
_root.areaAllyChance = 50;
_root.areaDamagePct = 100;
_root.areaEpicChance = 0;
_root.areaEpicChance2 = 0.1;
_root.challengeCompatible = true;
_root.challengeRewardMul = 1.11;
