//! status=pending
_root.areaSafe = false;
_root.areaUnderwater = false;
_root.areaSpawn = 10;
_root.areaSpawnReduce = 0;
_root.areaRareChance = 0;
_root.areaAllyChance = 0;
_root.areaDamagePct = 0;
_root.areaEpicChance = 0;
_root.areaEpicChance2 = 0;
diffText.text = "" + _root.save.arenaCorruptDifficulty;
bestDiffText.text = "[Best: " + _root.save.arenaCorruptBestDifficulty + "]";
_root.challengeCompatible = false;
