//! status=pending
_root.fightStat = "Castle Grimm";
_root.areaSafe = false;
_root.areaUnderwater = false;
_root.areaSpawn = 3.4;
_root.areaSpawnReduce = 25;
_root.areaRareChance = 4.5;
_root.areaAllyChance = 1;
_root.areaDamagePct = 12;
_root.areaEpicChance = 0.5;
_root.areaEpicChance2 = 2.6;
_root.areaFairyPerformance = 0;
_root.areaFairyPower = false;
_root.challengeCompatible = true;
_root.challengeRewardMul = 2.25;
