//! status=pending
function verif(username, saveID, refCode)
{
   if(_root.kongregate_username == username)
   {
      _root.verifyA = saveID;
      _root.verifyB = refCode;
   }
}
function addEvent(rating, year, month, date, eventName)
{
   _root.eventRating[year][month][date] += rating;
   _root.eventList[year][month][date][0] += 1;
   _root.eventList[year][month][date].push(eventName);
}
function overrideEvent(year, month, date)
{
   _root.eventRating[year][month][date] = 0;
   _root.eventList[year][month][date] = new Array();
   _root.eventList[year][month][date][0] = 0;
}
function displayEvent(year, month, date)
{
   temp = "";
   var _loc5_ = 1;
   while(_loc5_ <= _root.eventList[year][month][date][0])
   {
      temp += "* " + _root.eventList[year][month][date][_loc5_] + "\n";
      _loc5_ = _loc5_ + 1;
   }
   return temp;
}
function addRedCoin(user, amount, reason)
{
   if(_root.kongregate_username == user)
   {
      _root.contributorRC += amount;
      _root.rcEarnLog += "\n" + amount + " Red Coins / Reason: " + reason;
   }
}
function banhammer(user, reason)
{
   if(_root.kongregate_username == user || user == "[everyone]")
   {
      _root.canPlay = false;
      _root.banReason += reason + "\n";
   }
}
_root.verifyA = -1;
_root.verifyB = -1;
verif("Enyoeris",0,114858107);
verif("Rndom_Gy_159",0,186111787);
verif("Stormseeker71",0,156434967);
verif("Vidkid88",0,90837367);
verif("Cyrenics",0,115905707);
verif("DeamonElementia",0,102627127);
verif("ExSane",2,193916967);
verif("IlPadrino72",0,204503747);
verif("Wikke",0,85040647);
verif("Truzyxx",1,111615707);
verif("lolepolman",0,92694807);
verif("Mebbo",1,120636787);
verif("emokid69",0,133339037);
verif("BTlover",0,138602047);
verif("topher556",0,154085287);
verif("DJxJDx",1,121236617);
verif("Preebs",0,124711627);
verif("DragonJareth",0,146844287);
verif("irainsupreme",0,149346127);
verif("RebirthofJimmy",0,181795207);
verif("Youryou",0,153239457);
verif("Xfrogman43",0,199206707);
verif("nafia1",0,154947397);
verif("ildfugl",1,140313007);
verif("Xomps",0,166238527);
verif("ZahazaI",0,156945237);
verif("ladyunicornejg",1,158455887);
verif("GianniB5",0,143325487);
verif("Kibs",3,168976207);
verif("Sionyx",1,123011357);
verif("tohrik",0,165595367);
verif("Adamqs",1,186518557);
verif("falcorn",0,153593447);
verif("Dxb105",0,213443167);
verif("Karl7772000",0,177078337);
verif("b0terham",0,132152587);
verif("kasisu1910",0,141733357);
verif("figweb",1,166157747);
verif("Hyssop",0,125042187);
verif("cabbage42",0,153991087);
verif("IlPadrino72",3,204503747);
verif("adyman",0,225303557);
verif("Thedem",1,168316967);
verif("alberik",0,224303287);
verif("Nageki",3,165638207);
verif("ChampionofAiur",0,221247607);
verif("Dragunlord13",0,238917757);
verif("baaata",0,186818107);
verif("Connor98master",0,239298087);
verif("Kibs",0,168976207);
verif("laguna4ever",0,254923207);
verif("ForTexi",0,167817587);
verif("Mfgdjyb",0,193387207);
verif("MustardFTW",0,188922727);
verif("Dave1004",0,179597327);
verif("Jacob54321",0,199766707);
verif("diegowned",0,209723107);
verif("hawkcannon",0,238254567);
verif("minttheman",0,246965127);
verif("sprwalsh",0,184062067);
verif("Di684haha",3,238437127);
verif("Tuhats",0,167590507);
verif("123x1111",0,192953607);
verif("miller",0,213657537);
verif("AirSalad",0,178724567);
verif("johnlajoie",1,239823847);
verif("Mrmoocowman",0,201012707);
verif("ZahazaI",1,172824547);
verif("Cify",1,157972507);
verif("janvar",0,171371627);
verif("lokodoko",0,193187557);
verif("McGilroy",1,174030367);
verif("stingrayjayz",0,223386667);
verif("Soul_Reaper_25",0,223013287);
verif("cgrain",1,165638207);
verif("7g569d",0,227411387);
verif("kloip",0,207798657);
verif("paladari",0,220804487);
verif("JohnRipper",0,217450357);
verif("VTGames",1,229483347);
verif("Dragunlord13",1,238917757);
verif("ULTRAMAN21",0,235212327);
verif("hipersonic999",0,220914687);
verif("About84Waffles",1,230429227);
verif("Delekahni",0,224903687);
verif("soratti",0,206787527);
verif("TheTyfoon",0,198321907);
verif("DORGANN",0,211978447);
_root.eventList = new Array();
_root.eventRating = new Array();
i = 0;
while(i <= 9)
{
   _root.eventList[i] = new Array();
   _root.eventRating[i] = new Array();
   j = 1;
   while(j <= 12)
   {
      _root.eventList[i][j] = new Array();
      _root.eventRating[i][j] = new Array();
      k = 1;
      while(k <= 31)
      {
         _root.eventList[i][j][k] = new Array();
         _root.eventRating[i][j][k] = 0;
         _root.eventList[i][j][k][0] = 1;
         _root.eventList[i][j][k][1] = "Receive 10 Event Tokens every 5 minutes you play";
         k++;
      }
      j++;
   }
   i++;
}
i = 0;
while(i <= 9)
{
   addEvent(3,i,1,1,"Gain 100% more Coins from all sources except the Progress Bar, Garden, LolMarket and Fishing");
   addEvent(3,i,1,2,"Gain 100% more Coins from all sources except the Progress Bar, Garden, LolMarket and Fishing");
   addEvent(2,i,2,14,"Gain 50% more EXP from all sources except the Progress Bar, LolMarket and Awesome Adventures");
   addEvent(2,i,2,14,"Gain 50% more Coins from all sources except the Progress Bar, Garden, LolMarket and Fishing");
   addEvent(4,i,5,7,"Gain 200% more EXP from all sources except the Progress Bar, LolMarket and Awesome Adventures");
   addEvent(4,i,5,8,"Gain 200% more EXP from all sources except the Progress Bar, LolMarket and Awesome Adventures");
   addEvent(3,i,12,20,"Gain 100% more EXP from all sources except the Progress Bar, LolMarket and Awesome Adventures");
   addEvent(3,i,12,21,"Gain 100% more EXP from all sources except the Progress Bar, LolMarket and Awesome Adventures");
   addEvent(3,i,12,22,"Gain 100% more EXP from all sources except the Progress Bar, LolMarket and Awesome Adventures");
   addEvent(3,i,12,23,"Gain 100% more EXP from all sources except the Progress Bar, LolMarket and Awesome Adventures");
   addEvent(4,i,12,24,"Gain 200% more EXP from all sources except the Progress Bar, LolMarket and Awesome Adventures");
   addEvent(4,i,12,25,"Gain 200% more EXP from all sources except the Progress Bar, LolMarket and Awesome Adventures");
   addEvent(3,i,12,26,"Gain 100% more EXP from all sources except the Progress Bar, LolMarket and Awesome Adventures");
   addEvent(3,i,12,27,"Gain 100% more EXP from all sources except the Progress Bar, LolMarket and Awesome Adventures");
   addEvent(3,i,12,28,"Gain 100% more EXP from all sources except the Progress Bar, LolMarket and Awesome Adventures");
   addEvent(3,i,12,29,"Gain 100% more EXP from all sources except the Progress Bar, LolMarket and Awesome Adventures");
   addEvent(3,i,12,30,"Gain 100% more EXP from all sources except the Progress Bar, LolMarket and Awesome Adventures");
   addEvent(3,i,12,31,"Gain 100% more EXP from all sources except the Progress Bar, LolMarket and Awesome Adventures");
   addEvent(2,i,12,20,"Gain 50% more Coins from all sources except the Progress Bar, Garden, LolMarket and Fishing");
   addEvent(2,i,12,21,"Gain 50% more Coins from all sources except the Progress Bar, Garden, LolMarket and Fishing");
   addEvent(2,i,12,22,"Gain 50% more Coins from all sources except the Progress Bar, Garden, LolMarket and Fishing");
   addEvent(2,i,12,23,"Gain 50% more Coins from all sources except the Progress Bar, Garden, LolMarket and Fishing");
   addEvent(2,i,12,24,"Gain 50% more Coins from all sources except the Progress Bar, Garden, LolMarket and Fishing");
   addEvent(2,i,12,25,"Gain 50% more Coins from all sources except the Progress Bar, Garden, LolMarket and Fishing");
   addEvent(2,i,12,26,"Gain 50% more Coins from all sources except the Progress Bar, Garden, LolMarket and Fishing");
   addEvent(2,i,12,27,"Gain 50% more Coins from all sources except the Progress Bar, Garden, LolMarket and Fishing");
   addEvent(2,i,12,28,"Gain 50% more Coins from all sources except the Progress Bar, Garden, LolMarket and Fishing");
   addEvent(2,i,12,29,"Gain 50% more Coins from all sources except the Progress Bar, Garden, LolMarket and Fishing");
   addEvent(2,i,12,30,"Gain 50% more Coins from all sources except the Progress Bar, Garden, LolMarket and Fishing");
   addEvent(2,i,12,31,"Gain 50% more Coins from all sources except the Progress Bar, Garden, LolMarket and Fishing");
   addEvent(4,i,1,23,"2x Drop Rate in Battle Arena");
   addEvent(2,i,1,31,"1.5x Drop Rate in Battle Arena");
   addEvent(4,i,2,21,"2x Drop Rate in Battle Arena");
   addEvent(2,i,3,19,"1.5x Drop Rate in Battle Arena");
   addEvent(4,i,3,29,"2x Drop Rate in Battle Arena");
   addEvent(2,i,4,17,"1.5x Drop Rate in Battle Arena");
   addEvent(4,i,4,28,"2x Drop Rate in Battle Arena");
   addEvent(2,i,5,15,"1.5x Drop Rate in Battle Arena");
   addEvent(4,i,5,27,"2x Drop Rate in Battle Arena");
   addEvent(2,i,6,13,"1.5x Drop Rate in Battle Arena");
   addEvent(4,i,6,26,"2x Drop Rate in Battle Arena");
   addEvent(2,i,7,11,"1.5x Drop Rate in Battle Arena");
   addEvent(4,i,7,25,"2x Drop Rate in Battle Arena");
   addEvent(2,i,8,9,"1.5x Drop Rate in Battle Arena");
   addEvent(4,i,8,24,"2x Drop Rate in Battle Arena");
   addEvent(2,i,9,7,"1.5x Drop Rate in Battle Arena");
   addEvent(4,i,9,23,"2x Drop Rate in Battle Arena");
   addEvent(2,i,10,5,"1.5x Drop Rate in Battle Arena");
   addEvent(4,i,10,22,"2x Drop Rate in Battle Arena");
   addEvent(2,i,11,3,"1.5x Drop Rate in Battle Arena");
   addEvent(4,i,11,21,"2x Drop Rate in Battle Arena");
   addEvent(2,i,12,1,"1.5x Drop Rate in Battle Arena");
   addEvent(4,i,12,24,"2x Drop Rate in Battle Arena");
   addEvent(4,i,2,1,"4x Superior Crafting Material from loot drops in Battle Arena");
   addEvent(4,i,3,1,"4x Unobtainium from loot drops in Battle Arena");
   addEvent(4,i,5,1,"1.5x Career EXP gain");
   addEvent(4,i,6,1,"2.5x Drop Rate in Battle Arena");
   addEvent(4,i,7,1,"4x Green Coin from loot drops in Battle Arena");
   addEvent(4,i,8,1,"4x Blue Coin from loot drops in Battle Arena");
   addEvent(4,i,9,1,"4x Enhancer Fragment from loot drops in Battle Arena");
   addEvent(4,i,10,1,"4x Pixel from loot drops in Battle Arena");
   addEvent(4,i,11,1,"4x Crafting Material from loot drops in Battle Arena");
   addEvent(1,i,1,1,"Receive Event Tokens by claiming rewards");
   addEvent(3,i,1,1,"Daily Event Token limit is increased by 800");
   addEvent(1,i,2,14,"Receive Event Tokens by killing boss monsters");
   addEvent(3,i,2,14,"Daily Event Token limit is increased by 800");
   addEvent(1,i,5,7,"Receive Event Tokens by claiming rewards");
   addEvent(3,i,5,7,"Daily Event Token limit is increased by 800");
   addEvent(1,i,5,8,"Receive Event Tokens by claiming rewards");
   addEvent(3,i,5,8,"Daily Event Token limit is increased by 800");
   addEvent(1,i,10,30,"Receive Event Tokens by killing undead monsters");
   addEvent(1,i,10,30,"Daily Event Token limit is increased by 300");
   addEvent(1,i,10,31,"Receive Event Tokens by killing undead monsters");
   addEvent(1,i,10,31,"Daily Event Token limit is increased by 300");
   j = 1;
   while(j <= 12)
   {
      addEvent(1,i,j,3,"Progress Bar fills at full speed, even when Idle Mode is on");
      addEvent(1,i,j,6,"Wait time to harvest trees in Garden is reduced by 25%");
      addEvent(1,i,j,6,"Receive Event Tokens by harvesting trees");
      addEvent(1,i,j,6,"Daily Event Token limit is increased by 300");
      addEvent(1,i,j,8,"Gain 1.5x EXP from TukkunFCG");
      addEvent(1,i,j,8,"Receive Event Tokens by winning in TukkunFCG");
      addEvent(1,i,j,8,"Daily Event Token limit is increased by 300");
      addEvent(1,i,j,12,"Gain 1.5x EXP from Stadium");
      addEvent(1,i,j,12,"Receive Event Tokens by winning in Stadium");
      addEvent(1,i,j,12,"Daily Event Token limit is increased by 300");
      addEvent(1,i,j,14,"Gain 1.5x EXP from Fishing");
      addEvent(1,i,j,14,"Receive Event Tokens by fishing");
      addEvent(1,i,j,14,"Daily Event Token limit is increased by 300");
      addEvent(1,i,j,20,"Gain 1.5x EXP from Arcade");
      addEvent(1,i,j,20,"Receive Event Tokens by playing games in Arcade");
      addEvent(1,i,j,20,"Daily Event Token limit is increased by 300");
      addEvent(1,i,j,24,"Gain 1.5x EXP from Button Machine");
      addEvent(1,i,j,24,"Receive Event Tokens by pressing the Button Machine");
      addEvent(1,i,j,24,"Daily Event Token limit is increased by 300");
      addEvent(1,i,j,28,"Wait time for Adventure Energy is reduced by 25%");
      addEvent(1,i,j,28,"Receive Event Tokens by adventuring in Awesome Adventures");
      addEvent(1,i,j,28,"Daily Event Token limit is increased by 300");
      k = 1;
      while(k <= 31)
      {
         if((i + j + k) % 16 == 2)
         {
            addEvent(1,i,j,k,"Gain 1.5x EXP from Secret Dungeon area in Battle Arena");
         }
         if((i + j + k) % 16 == 6)
         {
            addEvent(1,i,j,k,"Gain 1.5x EXP from The Corruption area in Battle Arena");
         }
         if((i + j + k) % 16 == 10)
         {
            addEvent(1,i,j,k,"Gain 1.5x EXP from Endless Dungeon area in Battle Arena");
         }
         if((i + j + k) % 16 == 14)
         {
            addEvent(1,i,j,k,"Gain 1.5x EXP from The Corruption area in Battle Arena");
         }
         if(_root.eventRating[i][j][k] == 0)
         {
            if((i + j + k) % 8 <= 4)
            {
               addEvent(1,i,j,k,"Gain 25% more EXP from all sources except the Progress Bar, LolMarket and Awesome Adventures");
            }
            else
            {
               addEvent(1,i,j,k,"Gain 25% more Coins from all sources except the Progress Bar, Garden, LolMarket and Fishing");
            }
         }
         k++;
      }
      j++;
   }
   i++;
}
addEvent(10,7,6,5,"2.5x Drop Rate in Battle Arena");
addEvent(10,7,6,6,"Gain 50% more Coins from all sources except the Progress Bar, Garden, LolMarket and Fishing");
addEvent(10,7,6,7,"2.5x Drop Rate in Battle Arena");
addEvent(10,7,6,8,"Gain 50% more Coins from all sources except the Progress Bar, Garden, LolMarket and Fishing");
addEvent(10,7,6,9,"2.5x Drop Rate in Battle Arena");
addEvent(10,7,6,10,"Gain 50% more Coins from all sources except the Progress Bar, Garden, LolMarket and Fishing");
addEvent(10,7,6,11,"2.5x Drop Rate in Battle Arena");
addEvent(10,7,6,11,"Gain 50% more Coins from all sources except the Progress Bar, Garden, LolMarket and Fishing");
_root.todayEvent = 0;
_root.autoUpdateTime = [0,1354114800000,1356034320000,Infinity];
_root.challengeTime = [0,1374788220000,1390685820000,1393364220000,1398461820000,1427319420000,1469482620000,Infinity];
_root.eventStartTime = [0,1450810800000,1458154800000,1477335600000,Infinity];
_root.eventEndTime = [0,1451628000000,1459404000000,1478930400000,Infinity];
_root.eventArmorName = ["","Festive","Choco","Lantern",""];
_root.eventArmorFrame = [0,178,179,180,0];
_root.contributorRC = 0;
_root.rcEarnLog = _root.kongregate_username + "\'s Red Coin earning log:";
_root.banReason = "";
_root.canPlay = true;
banhammer("liooi","Using a bot to click the Button Machine way too much and destroying leaderboards - nearly 70% perfect clicks out of 15 million clicks.");
banhammer("1000deathz","Ascending 19 times in 11 days and getting too much EXP and destroying leaderboards.");
banhammer("baba1029","Having 225 million Garden EXP with less than 500 trees harvested and destroying leaderboards.");
banhammer("pingpong1","Unreasonable EXP gain rate.");
banhammer("emmett050","Unreasonable EXP gain rate.");
banhammer("hho1","Totally legitimate scores... no.");
banhammer("jksthe2nd","Reaching level 181 in TukkunFCG.");
banhammer("fabiogunit","Reaching level 200 in TukkunFCG.");
banhammer("lonestar1313","Destroying leaderboards. Many of them.");
banhammer("darkaos","Clicking the Button Machine way too much.");
banhammer("LODgunther","Ascending 1000 times.");
banhammer("sharkyscape","Getting way too much EXP.");
banhammer("Sallokin","Getting way too much EXP.");
banhammer("soonzzx","Getting way too much EXP.");
banhammer("J13H","Getting way too much EXP.");
banhammer("maxxox","Getting way too much EXP.");
banhammer("Gnomish","Getting way too much EXP.");
banhammer("cifaela","Getting way too much EXP.");
banhammer("kokokids","Getting way too much EXP.");
banhammer("draster","Getting way too much Garden EXP.");
banhammer("sharkyscape","Getting way too much Garden EXP.");
banhammer("Sallokin","Getting way too much Garden EXP.");
banhammer("Scithen","Getting way too much Garden EXP.");
banhammer("Jiby","Leaderboard hacking.");
banhammer("aetherdrom","Leaderboard hacking.");
banhammer("LLSF","Leaderboard hacking.");
banhammer("maredin","Leaderboard hacking.");
banhammer("edgefei","Leaderboard hacking.");
banhammer("RealFaker","Leaderboard hacking.");
banhammer("bazke","Leaderboard hacking.");
banhammer("celestior","Leaderboard hacking.");
banhammer("draster","Killing way too many monsters.");
banhammer("twiggy7711","Killing way too many monsters.");
banhammer("MagicChopstick","Killing 41 million monsters, over 90% of which are bosses, while looting only 1 million items. Seriously, it\'s not funny.");
banhammer("mikedp1","Impossible Arcade score.");
banhammer("chksec","Impossible Arcade score.");
banhammer("ZeoNFrosT","Impossible Arcade score.");
banhammer("Sansuki","Reaching level 200 in TukkunFCG.");
banhammer("masterzgar","Getting way too much LolMarket profit.");
banhammer("SweeneyTodd91","Hacking to get impossible raid scores.");
banhammer("mastermind_3000","Excessive hacking.");
banhammer("tmls12","Rebirthing 243 million times.");
banhammer("donkey4","Hacking.");
banhammer("CristianFarF","Hacking.");
addRedCoin("daf520",2000,"Completing Survey");
addRedCoin("Techwarrior",2000,"Completing Survey");
addRedCoin("holyvyse",2000,"Completing Survey");
addRedCoin("Mattgo90",2000,"Completing Survey");
addRedCoin("VuleJr",2000,"Completing Survey");
addRedCoin("sblabla",2000,"Completing Survey");
addRedCoin("meshwire",2000,"Completing Survey");
addRedCoin("galonski64",2000,"Completing Survey");
addRedCoin("Bench",2000,"Completing Survey");
addRedCoin("Trickymist98",2000,"Completing Survey");
addRedCoin("r6a3nky",2000,"Completing Survey");
addRedCoin("Thysiazo",2000,"Completing Survey");
addRedCoin("Toa_of_Pi",2000,"Completing Survey");
addRedCoin("baseballin",2000,"Completing Survey");
addRedCoin("Zorae",2000,"Completing Survey");
addRedCoin("aguspal",2000,"Completing Survey");
addRedCoin("tiktik",2000,"Completing Survey");
addRedCoin("Skyt",2000,"Completing Survey");
addRedCoin("alexwoody",2000,"Completing Survey");
addRedCoin("TFG50",2000,"Completing Survey");
addRedCoin("Hao368",2000,"Completing Survey");
addRedCoin("Darkranboria",2000,"Completing Survey");
addRedCoin("Aax5",2000,"Completing Survey");
addRedCoin("Ketchupyoshi",2000,"Completing Survey");
addRedCoin("Redjar978",2000,"Completing Survey");
addRedCoin("jefeesdios",2000,"Completing Survey");
addRedCoin("Aethereal",2000,"Completing Survey");
addRedCoin("mrkeki1",2000,"Completing Survey");
addRedCoin("Mephistic",2000,"Completing Survey");
addRedCoin("frae2",2000,"Completing Survey");
addRedCoin("EsotericaVirtue",2000,"Completing Survey");
addRedCoin("scarp",2000,"Completing Survey");
addRedCoin("Deathwing11",2000,"Completing Survey");
addRedCoin("Gramexer",2000,"Completing Survey");
addRedCoin("Feb2",2000,"Completing Survey");
addRedCoin("Jip137",2000,"Completing Survey");
addRedCoin("camperdave",2000,"Completing Survey");
addRedCoin("Kralis",2000,"Completing Survey");
addRedCoin("Luigi03",2000,"Completing Survey");
addRedCoin("Picklebreath",2000,"Completing Survey");
addRedCoin("slogsdon",2000,"Completing Survey");
addRedCoin("Barbaleki",2000,"Completing Survey");
addRedCoin("Xx1Zero1xX",2000,"Completing Survey");
addRedCoin("a1choi",2000,"Completing Survey");
addRedCoin("Huntragon",2000,"Completing Survey");
addRedCoin("Midknight226",2000,"Completing Survey");
addRedCoin("Enderjmu",2000,"Completing Survey");
addRedCoin("Finnis21",2000,"Completing Survey");
addRedCoin("Pokerhappy",2000,"Completing Survey");
addRedCoin("Uoteau",2000,"Completing Survey");
addRedCoin("Vigi",2000,"Completing Survey");
addRedCoin("Tigerh318",2000,"Completing Survey");
addRedCoin("Coolica",2000,"Completing Survey");
addRedCoin("heWhoPwns",2000,"Completing Survey");
addRedCoin("systempain",2000,"Completing Survey");
addRedCoin("Tramp_Boy_2",2000,"Completing Survey");
addRedCoin("mike2103",2000,"Completing Survey");
addRedCoin("linusn",2000,"Completing Survey");
addRedCoin("Bowshewicz",2000,"Completing Survey");
addRedCoin("MrPidgey",2000,"Completing Survey");
addRedCoin("xplodingpen3",2000,"Completing Survey");
addRedCoin("Darthlord",2000,"Completing Survey");
addRedCoin("Everyl",2000,"Completing Survey");
addRedCoin("CoCollect",2000,"Completing Survey");
addRedCoin("qlordz",2000,"Completing Survey");
addRedCoin("Caps_Lock",2000,"Completing Survey");
addRedCoin("Tonza0508",2000,"Completing Survey");
addRedCoin("ChioreanTudor",2000,"Completing Survey");
addRedCoin("Juski",2000,"Completing Survey");
addRedCoin("richardlycn013",2000,"Completing Survey");
addRedCoin("Pika2346",2000,"Completing Survey");
addRedCoin("TrinityX",2000,"Completing Survey");
addRedCoin("Bluji",2000,"Completing Survey");
addRedCoin("Pimgd",2000,"Completing Survey");
addRedCoin("Lordakin22",2000,"Completing Survey");
addRedCoin("dch247",2000,"Completing Survey");
addRedCoin("omoinoiadam",2000,"Completing Survey");
addRedCoin("Salvator",2000,"Completing Survey");
addRedCoin("Mebomb",1400,"Event Reward: Achievement Ideas");
addRedCoin("skykingcst",600,"Event Reward: Achievement Ideas");
addRedCoin("TheBeast88",800,"Event Reward: Achievement Ideas");
addRedCoin("Huntragon",400,"Event Reward: Achievement Ideas");
addRedCoin("MiniMissile",600,"Event Reward: Achievement Ideas");
addRedCoin("arrggg",400,"Event Reward: Achievement Ideas");
addRedCoin("Xx1Zero1xX",600,"Event Reward: Achievement Ideas");
addRedCoin("TotalMaverik",1200,"Event Reward: Achievement Ideas");
addRedCoin("CoCollect",800,"Event Reward: Achievement Ideas");
addRedCoin("JohnSteel",600,"Event Reward: Achievement Ideas");
addRedCoin("bladezor",400,"Event Reward: Achievement Ideas");
addRedCoin("tuqui",600,"Event Reward: Achievement Ideas");
addRedCoin("Yipiyuk",600,"Event Reward: Achievement Ideas");
addRedCoin("Toudou1620",600,"Event Reward: Achievement Ideas");
addRedCoin("logon",1000,"Event Reward: Achievement Ideas");
addRedCoin("Midknight226",600,"Event Reward: Achievement Ideas");
addRedCoin("Jerot",600,"Event Reward: Achievement Ideas");
addRedCoin("Skyt",1000,"Event Reward: Achievement Ideas");
addRedCoin("Ketchupyoshi",3200,"Event Reward: Achievement Ideas");
addRedCoin("MegaLamb",1000,"Event Reward: Achievement Ideas");
addRedCoin("Gabeee",600,"Event Reward: Achievement Ideas");
addRedCoin("Lordakin22",400,"Event Reward: Achievement Ideas");
addRedCoin("coco3366az",600,"Event Reward: Achievement Ideas");
addRedCoin("Darkruler2005",1000,"Event Reward: Achievement Ideas");
addRedCoin("dragonewyn",59000,"Being awesome.");
addRedCoin("SumYungGai",500,"Being awesome.");
addRedCoin("Salvator",1000,"Being awesome.");
addRedCoin("HeroicHero",1500,"Being awesome.");
addRedCoin("Postronicman",300,"Being awesome.");
addRedCoin("kirdaiht",2000,"Being awesome.");
addRedCoin("ChioreanTudor",2000,"Being awesome.");
addRedCoin("Toudou1620",2000,"Being awesome.");
addRedCoin("Ryo_Sangnoir",1500,"Being awesome.");
addRedCoin("Randomthought31",2000,"Being awesome.");
addRedCoin("CTSG",2000,"Being awesome.");
addRedCoin("truefire",3000,"Being awesome.");
addRedCoin("Darkranboria",2000,"Being awesome.");
addRedCoin("lobstershow",30000,"Being awesome.");
addRedCoin("CoCollect",40000,"Being awesome.");
addRedCoin("skykingcst",2000,"Being awesome.");
addRedCoin("Dzonis",800,"Being awesome.");
addRedCoin("SumYungGai",4000,"Art Contribution");
addRedCoin("Johannus",6000,"Art Contribution");
addRedCoin("Mike1108",5000,"Art Contribution");
addRedCoin("meshwire",4000,"Art Contribution");
addRedCoin("Dragonayzer",3000,"Art Contribution");
addRedCoin("FkidsPR",2000,"Art Contribution");
addRedCoin("mikemage",2000,"Refund for Maximum Boost bug");
addRedCoin("happyman12",2000,"Refund for Maximum Boost bug");
addRedCoin("MrManner",2000,"Refund for Maximum Boost bug");
addRedCoin("fa20",2000,"Refund for Maximum Boost bug");
addRedCoin("thaicoconut",2000,"Refund for Maximum Boost bug");
addRedCoin("ZAchaPi",2000,"Refund for Maximum Boost bug");
addRedCoin("The_BBoH",2000,"Refund for Maximum Boost bug");
addRedCoin("happyman12",2000,"Refund for Maximum Boost bug");
addRedCoin("tornado",2000,"Refund for Maximum Boost bug");
addRedCoin("Torgar",2000,"Refund for Maximum Boost bug");
addRedCoin("tiktik",2000,"Refund for Maximum Boost bug");
addRedCoin("Natamora",2000,"Refund for Maximum Boost bug");
addRedCoin("clanfish",2000,"Refund for Maximum Boost bug");
addRedCoin("commendertrent",2000,"Refund for Maximum Boost bug");
addRedCoin("KittehLover",4000,"Bug Report: Dropping Max Boost");
addRedCoin("Skyt",5000,"Bug Report: Infinity Boost");
addRedCoin("Darkruler2005",3000,"Bug Report: Infinity Boost");
addRedCoin("CoCollect",4500,"Useful suggestion");
addRedCoin("Bluji",3000,"Bug Report: Undefined reward");
addRedCoin("coldkick",3000,"Bug Report: Super Battery exploit");
addRedCoin("liosfan",700,"Completing Survey: v1300 - Battle Arena / Arcade balancing");
addRedCoin("jew4life520",700,"Completing Survey: v1300 - Battle Arena / Arcade balancing");
addRedCoin("PokerHappy",1000,"Completing Survey: v1300 - Battle Arena / Arcade balancing");
addRedCoin("SpectralFlame",1000,"Completing Survey: v1300 - Battle Arena / Arcade balancing");
addRedCoin("Bench",1000,"Completing Survey: v1300 - Battle Arena / Arcade balancing");
addRedCoin("7smartone7",700,"Completing Survey: v1300 - Battle Arena / Arcade balancing");
addRedCoin("Meepoo",700,"Completing Survey: v1300 - Battle Arena / Arcade balancing");
addRedCoin("KittehLover",1000,"Completing Survey: v1300 - Battle Arena / Arcade balancing");
addRedCoin("RikuFrost",1000,"Completing Survey: v1300 - Battle Arena / Arcade balancing");
addRedCoin("aguspal",1000,"Completing Survey: v1300 - Battle Arena / Arcade balancing");
addRedCoin("badgecrasher",1000,"Never gonna give you up...");
addRedCoin("Balrogon",1000,"Never gonna give you up...");
addRedCoin("XJoschYZ",1000,"Never gonna give you up...");
addRedCoin("HeroicHero",3500,"Art Contribution");
addRedCoin("gameinsky",5500,"Technical Help");
addRedCoin("macseber",2500,"Bug Report: False monster encounter");
addRedCoin("player2010abc",2000,"Bug Report: False monster encounter");
addRedCoin("masterman229",2000,"Bug Report: False monster encounter");
addRedCoin("Ligarius",3500,"Bug Report: Cannot purchase Stadium");
addRedCoin("marina32121",2000,"Bug Report: Unable to change title");
addRedCoin("cyclops398",2000,"Bug Report: Unable to kill Grinning Colossus");
addRedCoin("SpectralFlame",1500,"Bug Report: False \'No Knockback\' upgrades.");
addRedCoin("Skyt",1500,"derp derp derp");
addRedCoin("SpectralFlame",1500,"derp derp derp");
addRedCoin("loli_slayer",700,"Bug Report: False skill book display");
addRedCoin("gem85",700,"Bug Report: False monster name");
addRedCoin("Makilio",1500,"Bug Report: False skill book drop");
addRedCoin("Toa_of_Pi",1500,"Bug Report: Unlimited oxygen");
addRedCoin("zamble",1500,"Useful suggestion");
addRedCoin("SpectralFlame",1500,"Useful suggestion");
addRedCoin("zamble",1500,"Useful suggestion");
addRedCoin("loli_slayer",1500,"Useful suggestion");
addRedCoin("SlasherX",1500,"Useful suggestion");
addRedCoin("RebornStupidity",1500,"Account switching (SlasherX)");
addRedCoin("SpectralFlame",500,"Blah.");
addRedCoin("freist",2000,"Bug Report: Epic Skills can be upgraded over max level");
addRedCoin("fooods",1000,"Useful suggestion");
addRedCoin("Skyt",1000,"Useful suggestion");
addRedCoin("marina32121",500,"Bug Report: Test Pet feed display");
addRedCoin("sabbut",900,"[Test Version] Bug Report: Typo in item description");
addRedCoin("KittehLover",900,"[Test Version] Bug Report: Konami Code not working");
addRedCoin("Meepoo",600,"Event Reward: Naming Contest #3");
addRedCoin("elchesko",900,"Event Reward: Naming Contest #3");
addRedCoin("Piscataway44",700,"Event Reward: Naming Contest #3");
addRedCoin("MrManner",800,"Event Reward: Naming Contest #3");
addRedCoin("pewbe",500,"Event Reward: Naming Contest #3");
addRedCoin("Pimgd",500,"Event Reward: Naming Contest #3");
addRedCoin("wecl0me12",500,"Event Reward: Naming Contest #3");
addRedCoin("Toa_of_Pi",600,"Event Reward: Naming Contest #3");
addRedCoin("Laxaria",700,"Event Reward: Naming Contest #3");
addRedCoin("Mebomb",600,"Event Reward: Naming Contest #3");
addRedCoin("Bench",600,"Event Reward: Naming Contest #3");
addRedCoin("Bluji",400,"Event Reward: Naming Contest #3");
addRedCoin("Norhede",700,"Event Reward: Naming Contest #3");
addRedCoin("SpectralFlame",700,"Event Reward: Naming Contest #3");
addRedCoin("Thystonius",600,"Event Reward: Naming Contest #3");
addRedCoin("Blauw",600,"Event Reward: Naming Contest #3");
addRedCoin("Vara",600,"Event Reward: Naming Contest #3");
addRedCoin("gem85",600,"Event Reward: Naming Contest #3");
addRedCoin("freist",700,"Event Reward: Naming Contest #3");
addRedCoin("cuspcham",500,"Event Reward: Naming Contest #3");
addRedCoin("SirStopp",600,"Event Reward: Naming Contest #3");
addRedCoin("PlayerPimp",600,"Event Reward: Naming Contest #3");
addRedCoin("zeo123200",700,"Event Reward: Naming Contest #3");
addRedCoin("DuncmanG",700,"Event Reward: Naming Contest #3");
addRedCoin("awein999",600,"Event Reward: Naming Contest #3");
addRedCoin("sabbut",800,"Event Reward: Naming Contest #3");
addRedCoin("Pokerhappy",700,"Event Reward: Naming Contest #3");
addRedCoin("liosfan",600,"Event Reward: Naming Contest #3");
addRedCoin("soultaker7777",600,"Event Reward: Naming Contest #3");
addRedCoin("missingno",700,"Event Reward: Naming Contest #3");
addRedCoin("marina32121",600,"Event Reward: Naming Contest #3");
addRedCoin("pinkluver296",600,"Event Reward: Naming Contest #3");
addRedCoin("highscore",600,"Event Reward: Naming Contest #3");
addRedCoin("Angried",700,"Event Reward: Naming Contest #3");
addRedCoin("Terichan",700,"Event Reward: Naming Contest #3");
addRedCoin("RikuFrost",600,"Event Reward: Naming Contest #3");
addRedCoin("XenorBlight",600,"Event Reward: Naming Contest #3");
addRedCoin("durfat",600,"Event Reward: Naming Contest #3");
addRedCoin("Toudou1620",600,"Event Reward: Naming Contest #3");
addRedCoin("azurebalmung",600,"Event Reward: Naming Contest #3");
addRedCoin("Postronicman",600,"Event Reward: Naming Contest #3");
addRedCoin("Stompy40",600,"Event Reward: Naming Contest #3");
addRedCoin("phyroxx",600,"Event Reward: Naming Contest #3");
addRedCoin("lennonluiz0907",400,"Event Reward: Naming Contest #3");
addRedCoin("fooods",1000,"Bug report: Mega Rampage doesn\'t work with ranged weapons");
addRedCoin("loli_slayer",1000,"Bug report: Negative healing");
addRedCoin("DuncmanG",1000,"Bug report: Monsters drop weapons on Easy Mode.");
addRedCoin("lennonluiz0907",500,"Bug report: Cannot have 0 Pixels remaining");
addRedCoin("Pimgd",500,"Bug report: False Battle Arena color display");
addRedCoin("loli_slayer",1000,"Bug report: Idle Mode doesn\'t reward. [Bug fixed, was a rare bug which was caused by the bar having exactly 224.00 pixels in width.]");
addRedCoin("Tukkun",100000,"Testing purposes.");
addRedCoin("burningpee123",1000,"[Test Version] Bug Report: Shop doesn\'t refresh");
addRedCoin("Yamiro",1000,"[Test Version] Bug Report: False Megaboss killcount");
addRedCoin("Makilio",1000,"[Test Version] Bug Report: \'Earn X achievements\' achievements don\'t work");
addRedCoin("Richirdo",500,"[Test Version] Bug Report: Cursor is invisible in pause screen.");
addRedCoin("Bluji",1000,"[Test Version] Bug Report: Broken pet hunger.");
addRedCoin("7smartone7",500,"[Test Version] Bug Report: False TukkunFCG display");
addRedCoin("loli_slayer",500,"[Test Version] Bug Report: NaN level for untouched savefiles");
addRedCoin("Mebomb",500,"[Test Version] Bug Report: Potion display");
addRedCoin("loli_slayer",500,"[Test Version] Bug Report: Cannot view certain shop items");
addRedCoin("Makilio",1000,"[Test Version] Bug Report: Shops in the Battle Arena cannot be seen.");
addRedCoin("SpectralFlame",2000,"[Test Version] Bug Report: Free access to Secret Lab");
addRedCoin("Toa_of_Pi",500,"[Test Version] Bug Report: Ability to access page 2 of Bonus Shop");
addRedCoin("ForceofLight",2000,"[Test Version] Bug Report: Undefined FCG card");
addRedCoin("wecl0me12",500,"[Test Version] Bug Report: TukkunFCG is a blank screen");
addRedCoin("loli_slayer",500,"[Test Version] Bug Report: Cannot access Money Printer");
addRedCoin("gem85",1000,"[Test Version] Bug Report: (Minor display bugs)");
addRedCoin("SpectralFlame",2000,"[Test Version] Bug Report: Free access to Time Machine");
addRedCoin("SpectralFlame",500,"[Test Version] Bug Report: False adventure event");
addRedCoin("Bench",1000,"[Test Version] Bug Report: Time Machine doesn\'t work");
addRedCoin("XxCradx",1000,"[Test Version] Bug Report: False popup in the TukkunFCG");
addRedCoin("Darkranboria",2000,"Area Design: The Desert");
addRedCoin("Freak40808",2000,"Area Design: Binary Battlefield");
addRedCoin("Freak40808",2000,"Area Design: Safe Zone");
addRedCoin("Freak40808",2000,"Area Design: Pirate Ship");
addRedCoin("Freak40808",2000,"Area Design: Night Forest");
addRedCoin("Gama11",2750,"Area Design: Ropeless Room");
addRedCoin("Gama11",2750,"Area Design: Dark Portal");
addRedCoin("hpmons",2000,"Area Design: Secret Beach");
addRedCoin("megooshnish",2000,"Area Design: Prehistoric Area");
addRedCoin("meshwire",2000,"Area Design: Volcano Peak");
addRedCoin("meshwire",2000,"Area Design: Frosty Zone");
addRedCoin("Mike1108",7000,"Area Design: 2012");
addRedCoin("Skyt",2000,"Area Design: Dark Pyramid");
addRedCoin("TARDIS",2000,"Area Design: The Sky");
addRedCoin("TheSullen",2000,"Area Design: Training Zone");
addRedCoin("TheSullen",2000,"Area Design: Deadlands");
addRedCoin("TheSullen",2000,"Area Design: Mystic Forest");
addRedCoin("TheSullen",2000,"Area Design: Dragon Cave");
addRedCoin("Toudou1620",2000,"Area Design: Pirate Ship Interior");
addRedCoin("UpsetFisherMAN",3250,"Area Design: The Beach");
addRedCoin("WolfWarhead",2000,"Area Design: Scary Graveyard");
addRedCoin("WolfWarhead",2000,"Area Design: Mystic Path");
addRedCoin("napadan",2000,"Art Contribution");
addRedCoin("Terichan",1500,"Useful suggestion");
addRedCoin("Thegreywarden",500,"Useful suggestion");
addRedCoin("Darcouth",500,"Useful suggestion");
addRedCoin("Jesto",1700,"Event Reward: Create Your Own Adventure!");
addRedCoin("Bluji",500,"Event Reward: Create Your Own Adventure!");
addRedCoin("daf420",400,"Event Reward: Create Your Own Adventure!");
addRedCoin("sabbut",500,"Event Reward: Create Your Own Adventure!");
addRedCoin("Huntragon",500,"Event Reward: Create Your Own Adventure!");
addRedCoin("loli_slayer",200,"Event Reward: Create Your Own Adventure!");
addRedCoin("DragonArcherZ",600,"Event Reward: Create Your Own Adventure!");
addRedCoin("Mebomb",400,"Event Reward: Create Your Own Adventure!");
addRedCoin("wecl0me12",500,"Event Reward: Create Your Own Adventure!");
addRedCoin("Skyt",700,"Bug report: \'undefined\' loot items");
addRedCoin("ABlindOrphan",1500,"Art Contribution");
addRedCoin("ABlindOrphan",1500,"Art Contribution");
addRedCoin("TwoPlusTwo",1500,"Bug report: \'Attack Removal\' card works falsely");
addRedCoin("felipe970421",1500,"Exploit report: Tab + Enter abuse to charge battery");
addRedCoin("EinAnderer",700,"Bug report: Boost bars provide no info");
addRedCoin("Boligao",1500,"Bug report: Invisible cursor in main menu");
addRedCoin("a20365354",1500,"Bug report: TukkunFCG layer issue");
addRedCoin("Prongs",2000,"Bug report: Save slot 3 is broken");
addRedCoin("iwongames99",2000,"Bug report: Save slot 3 is broken");
addRedCoin("max192",1500,"Bug report: Insta-Progress costs nothing");
addRedCoin("Jesto",3500,"Exploit report: Free Insta-Progress and Insta-EXP");
addRedCoin("Zelja",3500,"Exploit report: Pixel Bonus abuse in Dimensional Room");
addRedCoin("ABlindOrphan",3000,"Area Design: Smiley Island");
addRedCoin("aznpanda890",2500,"Bug report: NaN Pixel gain");
addRedCoin("MerrimanLyon",2000,"Bug report: NaN Pixel gain");
addRedCoin("tenco1",700,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("Smaland47",700,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("Kenaron",700,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("Sturmfeder",600,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("justinkal",600,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("missingno",600,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("ChaosII7",600,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("Motztante",600,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("Vexsloth",600,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("jakxkidney",600,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("DragonArcherZ",600,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("figter2000",600,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("39kk9t",600,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("soultaker7777",600,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("SaintSpirit",600,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("Tsunoflare",600,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("vincenthi135799",600,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("Gamer4124",600,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("Piscataway44",600,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("Aurian",200,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("destroyer57345",600,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("Rieffu",600,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("timhessel",600,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("39kk9t",600,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("jurrin",500,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("Purgexcross",500,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("straymaverick",500,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("adrian206",500,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("DavidMadsen",500,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("balrok",500,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("duudez",500,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("frae2",500,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("Yupei",500,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("huadianz",500,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("Hakaisha",500,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("iamevilman",500,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("shinki12345",500,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("nightmaren00",500,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("Gamerdude247",500,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("Alamand",400,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("lackinglack1",400,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("Killerkarnickel",400,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("epseudoo",400,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("aznpanda890",400,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("Tigerbladedn",400,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("elkid",400,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("ManXl",400,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("zeo123200",400,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("LokiGodOfFire",400,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("xdarkcodex",400,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("Fasalrod",400,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("crazyphysicist",400,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("C4po",400,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("zerotg90",400,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("RikuFrost",400,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("rocxror",400,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("Abinmorth",400,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("dahp",400,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("Nator",400,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("Sephirothfan",400,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("metax11",400,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("opex51",400,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("arklegru",400,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("Mirodian",400,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("pika393",400,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("Odenezen",400,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("hithere",400,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("Qwertyuiopas",400,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("Mindtruster",400,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("trofffim",400,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("JohnSmithBalls",400,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("drakethatsme",400,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("nickthemenace",400,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("torcherboy10",300,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("iamnoone",300,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("person2348",300,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("Quaznar",300,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("sh00td3ad",300,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("Simpoink",300,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("abc12367659",300,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("Olobaid",300,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("GregLazlo",300,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("spyrolvr96",300,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("AogT666",300,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("Arcanmster",300,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("jeff7871",300,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("mmKALLL",300,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("cheese9999",300,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("pagboy",300,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("blakzer",300,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("isomanic",200,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("Woon1957",200,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("florian887",200,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("codyman1234",200,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("levak2",200,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("Bluji",200,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("HolyFang",200,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("Ryo_Sangnoir",200,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("Squigglet",200,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("vjeff93",200,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("isomanic",200,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("ddelorenzo",200,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("starhaunter",200,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("florrat",200,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("gagataz",200,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("kwek",200,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("logo2462",200,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("hyperhippy92",200,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("antibarba",200,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("sabbut",200,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("CANNONBALL56",200,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("Althaleus",200,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("ktrout42",200,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("xAngelx",200,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("ddueber",200,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("James1011R",200,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("fakeandfailure",200,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("jakxkidney",200,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("ForceofLight",200,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("MrSlap",200,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("kenneth2830",200,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("SFgame",200,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("shinki12345",200,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("not4u",200,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("Bowshewicz",200,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("killaofgames280",200,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("zieger",200,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("jpalange",200,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("chippi",200,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("ildfugl",200,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("simpman",200,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("Galanor",200,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("bunjun",200,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("HowlingHatake",200,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("mulquist",200,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("Grungeking",200,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("Flamerai",200,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("Enderless",200,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("Bench",200,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("accordingleaf",200,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("mentalman284",200,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("tsjak",200,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("Lazarus",200,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("gshowfan199",200,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("Kakerlake",200,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("deathangel20",200,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("TwoPlusTwo",200,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("Beeshrine09",200,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("seabird500",200,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("xxhenleaxx",200,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("xLightx",200,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("figter2000",200,"Event Reward: Submit Your TukkunFCG Decks!");
addRedCoin("SW1134",50,"LOL");
addRedCoin("Blackwaltz002",3300,"TukkunFCG Card Design");
addRedCoin("James1011R",1100,"Bug Report: Negative damage causing weird ability (Note: Don\'t talk on the forums about this)");
addRedCoin("pika393",1100,"Bug Report: TukkunFCG opponents giving wrong rewards");
addRedCoin("Yupei",200,"Activity #1 Winner");
addRedCoin("glfootballmlb21",200,"Activity #1 Winner");
addRedCoin("Angried",200,"Activity #1 Winner");
addRedCoin("Sorvius",-15000,"Item \'Design\'");
addRedCoin("Sallygwizz37",-60000,"Item \'Design\'");
addRedCoin("Sallygwizz37",-30000,"Spamming in the forum");
addRedCoin("OnlineHackers",-2000000,"Misspelling \'subscribe\'");
addRedCoin("TukkunIsLame",-4000000,"Not remembering to hide the leaderboards in a certain Youtube video.");
addRedCoin("skagkiller56",-1000000,"Hacking promotion");
addRedCoin("zammy99",-1000000,"Hacking promotion");
addRedCoin("pick_pocket_689",-1000000,"Hacking promotion");
addRedCoin("gr2mm",-1000000,"Hacking promotion");
addRedCoin("failure2d",-100000,"Epic failure");
addRedCoin("GigaDramon",-100000000,"Epic failure");
addRedCoin("i_am_king_2",-100000,"Epic failure");
addRedCoin("klipimong",-100000,"Epic failure");
addRedCoin("clickytaco",-100000,"Epic failure");
addRedCoin("supermario007",-100000,"Epic failure");
addRedCoin("gavin_rox_3",-100000,"Epic failure");
addRedCoin("BLOOD300",-10000000,"Epic failure");
addRedCoin("zildaa",-100000,"Epic failure");
addRedCoin("THE_BEST_HACKER",-100000,"Epic failure");
addRedCoin("osm70",-10000000,"");
addRedCoin("epictrull",-10000000,"");
addRedCoin("NobsiA",-10000000,"Hacking and bragging about it in the forum");
addRedCoin("Gama11",2000,"Area Design: Area 51");
addRedCoin("Squigglet",3000,"Area Design: Coral Reef");
addRedCoin("Axianamos",4000,"Area Design: Dark Pyramid");
addRedCoin("zwander",2000,"Area Design: Dark Pyramid (+)");
addRedCoin("Squigglet",3000,"Area Design: Deserted Alley");
addRedCoin("uberuber22",3000,"Area Design: Destroyed Battlefield");
addRedCoin("Randomthought31",3000,"Area Design: Dragon Cave");
addRedCoin("DistinctEvil",3000,"Area Design: Evil Forest");
addRedCoin("ManaMiyavi",3000,"Area Design: Exotic Canopy");
addRedCoin("Timurlenk",4000,"Area Design: ???");
addRedCoin("UpsetFisherMAN",3000,"Area Design: Forbidden Fortress");
addRedCoin("DistinctEvil",3000,"Area Design: Gold Mine");
addRedCoin("UpsetFisherMAN",3000,"Area Design: Hell");
addRedCoin("BorisFreaman",3000,"Area Design: Modern Graveyard");
addRedCoin("Randomthought31",3000,"Area Design: Mono Town");
addRedCoin("Randomthought31",3000,"Area Design: Mystic Forest");
addRedCoin("maadneet",3000,"Area Design: Near The \'??? Generator\'");
addRedCoin("Randomthought31",2000,"Area Design: Night Forest");
addRedCoin("ChaosII7",4000,"Area Design: Not Copyright Infringement");
addRedCoin("MaxDragon",3000,"Area Design: Old Ruins");
addRedCoin("Richirdo",3000,"Area Design: Old Ruins Entrance");
addRedCoin("Gama11",3000,"Area Design: Pirate Ship Interior");
addRedCoin("BIGTIPPER",3000,"Area Design: Polluted Sky");
addRedCoin("ChaosII7",4000,"Area Design: Secret Lab");
addRedCoin("AirSalad",3000,"Area Design: Sonic");
addRedCoin("Squigglet",3000,"Area Design: Spooky Crypt");
addRedCoin("Randomthought31",2000,"Area Design: Swamp Hop");
addRedCoin("Randomthought31",3000,"Area Design: The Desert");
addRedCoin("ChaosII7",4000,"Area Design: The Sky");
addRedCoin("Randomthought31",3000,"Area Design: Whale Beach");
addRedCoin("MaxDragon",4000,"Area Design: Ye Olde Pub");
addRedCoin("zwander",3000,"Area Design: 3001 Wasteland");
addRedCoin("Bluji",200,"Completing Survey: Arena Enhancement System");
addRedCoin("0Crapknocker0",200,"Completing Survey: Arena Enhancement System");
addRedCoin("sabbut",200,"Completing Survey: Arena Enhancement System");
addRedCoin("lyghtcrye",200,"Completing Survey: Arena Enhancement System");
addRedCoin("BIGTIPPER",200,"Completing Survey: Arena Enhancement System");
addRedCoin("InfernalSilence",200,"Completing Survey: Arena Enhancement System");
addRedCoin("Andiiboi",200,"Completing Survey: Arena Enhancement System");
addRedCoin("Wgurgh",200,"Completing Survey: Arena Enhancement System");
addRedCoin("LucasBurgel",200,"Completing Survey: Arena Enhancement System");
addRedCoin("hamstercrap",200,"Completing Survey: Arena Enhancement System");
addRedCoin("Duckboii",200,"Completing Survey: Arena Enhancement System");
addRedCoin("Piscataway44",200,"Completing Survey: Arena Enhancement System");
addRedCoin("metax11",200,"Completing Survey: Arena Enhancement System");
addRedCoin("xstinkweedx",200,"Completing Survey: Arena Enhancement System");
addRedCoin("Psycroth",200,"Completing Survey: Arena Enhancement System");
addRedCoin("SvartRuskTroll",200,"Completing Survey: Arena Enhancement System");
addRedCoin("Darkruler2005",200,"Completing Survey: Arena Enhancement System");
addRedCoin("jjjuu",200,"Completing Survey: Arena Enhancement System");
addRedCoin("dariofg",200,"Completing Survey: Arena Enhancement System");
addRedCoin("koozkie",200,"Completing Survey: Arena Enhancement System");
addRedCoin("nickthemenace",200,"Completing Survey: Arena Enhancement System");
addRedCoin("ChaosII7",200,"Completing Survey: Arena Enhancement System");
addRedCoin("Eniamar",200,"Completing Survey: Arena Enhancement System");
addRedCoin("Cerbius",200,"Completing Survey: Arena Enhancement System");
addRedCoin("Arch_Gremlin",200,"Completing Survey: Arena Enhancement System");
addRedCoin("Benzopyrene",200,"Completing Survey: Arena Enhancement System");
addRedCoin("Mebomb",200,"Completing Survey: Arena Enhancement System");
addRedCoin("Aurian",200,"Completing Survey: Arena Enhancement System");
addRedCoin("maadneet",200,"Completing Survey: Arena Enhancement System");
addRedCoin("macseber",200,"Completing Survey: Arena Enhancement System");
addRedCoin("Rappoman",200,"Completing Survey: Arena Enhancement System");
addRedCoin("Toa_of_Pi",200,"Completing Survey: Arena Enhancement System");
addRedCoin("TREZAtreza",200,"Completing Survey: Arena Enhancement System");
addRedCoin("zuton97",200,"Completing Survey: Arena Enhancement System");
addRedCoin("murgatroid99",200,"Completing Survey: Arena Enhancement System");
addRedCoin("TwoPlusTwo",200,"Completing Survey: Arena Enhancement System");
addRedCoin("Asrial",200,"Completing Survey: Arena Enhancement System");
addRedCoin("Odenezen",200,"Completing Survey: Arena Enhancement System");
addRedCoin("James1011R",200,"Completing Survey: Arena Enhancement System");
addRedCoin("Angried",200,"Completing Survey: Arena Enhancement System");
addRedCoin("chevalerie94",200,"Completing Survey: Arena Enhancement System");
addRedCoin("richardlycn013",200,"Completing Survey: Arena Enhancement System");
addRedCoin("Gama11",200,"Completing Survey: Arena Enhancement System");
addRedCoin("Barrak",200,"Completing Survey: Arena Enhancement System");
addRedCoin("DarkDespair5",200,"Completing Survey: Arena Enhancement System");
addRedCoin("MiniMissile",200,"Completing Survey: Arena Enhancement System");
addRedCoin("eXoDoX",200,"Completing Survey: Arena Enhancement System");
addRedCoin("DistinctEvil",200,"Completing Survey: Arena Enhancement System");
addRedCoin("f1pokerspeed",200,"Completing Survey: Arena Enhancement System");
addRedCoin("TheGuardianAngel",200,"Completing Survey: Arena Enhancement System");
addRedCoin("starhaunter",200,"Completing Survey: Arena Enhancement System");
addRedCoin("Spire115",200,"Completing Survey: Arena Enhancement System");
addRedCoin("Sparloki",200,"Completing Survey: Arena Enhancement System");
addRedCoin("weslleyend",200,"Completing Survey: Arena Enhancement System");
addRedCoin("YYZ133",200,"Completing Survey: Arena Enhancement System");
addRedCoin("Silencing",200,"Completing Survey: Arena Enhancement System");
addRedCoin("zandroid",200,"Completing Survey: Arena Enhancement System");
addRedCoin("IiroOnPerse",200,"Completing Survey: Arena Enhancement System");
addRedCoin("ManaMiyavi",200,"Completing Survey: Arena Enhancement System");
addRedCoin("MushroomHermit",200,"Completing Survey: Arena Enhancement System");
addRedCoin("rcktzr",200,"Completing Survey: Arena Enhancement System");
addRedCoin("Deathborn668",200,"Completing Survey: Arena Enhancement System");
addRedCoin("markboy11",200,"Completing Survey: Arena Enhancement System");
addRedCoin("helloAAAAA",200,"Completing Survey: Arena Enhancement System");
addRedCoin("Jojhy",200,"Completing Survey: Arena Enhancement System");
addRedCoin("Sturmfeder",200,"Completing Survey: Arena Enhancement System");
addRedCoin("Majildian",200,"Completing Survey: Arena Enhancement System");
addRedCoin("Huntragon",200,"Completing Survey: Arena Enhancement System");
addRedCoin("tenco1",200,"Completing Survey: Arena Enhancement System");
addRedCoin("Zox457",200,"Completing Survey: Arena Enhancement System");
addRedCoin("theyareclose",200,"Completing Survey: Arena Enhancement System");
addRedCoin("Cakeofdoom",200,"Completing Survey: Arena Enhancement System");
addRedCoin("soultaker7777",200,"Completing Survey: Arena Enhancement System");
addRedCoin("slogsdon",200,"Completing Survey: Arena Enhancement System");
addRedCoin("wecl0me12",200,"Completing Survey: Arena Enhancement System");
addRedCoin("wiifreak20",200,"Completing Survey: Arena Enhancement System");
addRedCoin("destroyer57345",200,"Completing Survey: Arena Enhancement System");
addRedCoin("iopghj",200,"Completing Survey: Arena Enhancement System");
addRedCoin("Truub",200,"Completing Survey: Arena Enhancement System");
addRedCoin("milleraus10",200,"Completing Survey: Arena Enhancement System");
addRedCoin("Pika2346",200,"Completing Survey: Arena Enhancement System");
addRedCoin("JimmyTheSqealer",200,"Completing Survey: Arena Enhancement System");
addRedCoin("Shorgun",200,"Completing Survey: Arena Enhancement System");
addRedCoin("tony526",200,"Completing Survey: Arena Enhancement System");
addRedCoin("hotdog911",200,"Completing Survey: Arena Enhancement System");
addRedCoin("bonecrusher1022",200,"Completing Survey: Arena Enhancement System");
addRedCoin("Prongs",200,"Completing Survey: Arena Enhancement System");
addRedCoin("fireballzsss",200,"Completing Survey: Arena Enhancement System");
addRedCoin("Motters",200,"Completing Survey: Arena Enhancement System");
addRedCoin("niky45",200,"Completing Survey: Arena Enhancement System");
addRedCoin("UpsetFisherMAN",200,"Completing Survey: Arena Enhancement System");
addRedCoin("Keap12",200,"Completing Survey: Arena Enhancement System");
addRedCoin("Miguelin1317",200,"Completing Survey: Arena Enhancement System");
addRedCoin("MadSniper",200,"Completing Survey: Arena Enhancement System");
addRedCoin("jonaxan",200,"Completing Survey: Arena Enhancement System");
addRedCoin("etmoonshade",200,"Completing Survey: Arena Enhancement System");
addRedCoin("Supereert",200,"Completing Survey: Arena Enhancement System");
addRedCoin("Mindtruster",200,"Completing Survey: Arena Enhancement System");
addRedCoin("evilnerd",200,"Completing Survey: Arena Enhancement System");
addRedCoin("Yupei",200,"Completing Survey: Arena Enhancement System");
addRedCoin("felipe970421",200,"Completing Survey: Arena Enhancement System");
addRedCoin("michael222",200,"Completing Survey: Arena Enhancement System");
addRedCoin("somethingggg",200,"Completing Survey: Arena Enhancement System");
addRedCoin("duudez",200,"Completing Survey: Arena Enhancement System");
addRedCoin("simplymac",200,"Completing Survey: Arena Enhancement System");
addRedCoin("joel_d",200,"Completing Survey: Arena Enhancement System");
addRedCoin("Puyoyoshi",200,"Completing Survey: Arena Enhancement System");
addRedCoin("pinguin333",200,"Completing Survey: Arena Enhancement System");
addRedCoin("santifrey",200,"Completing Survey: Arena Enhancement System");
addRedCoin("Dataman",200,"Completing Survey: Arena Enhancement System");
addRedCoin("missingno",200,"Completing Survey: Arena Enhancement System");
addRedCoin("juckter",200,"Completing Survey: Arena Enhancement System");
addRedCoin("Ligarius",200,"Completing Survey: Arena Enhancement System");
addRedCoin("Ryo_Sangnoir",200,"Completing Survey: Arena Enhancement System");
addRedCoin("TheToaOfTaKoro",200,"Completing Survey: Arena Enhancement System");
addRedCoin("some123",200,"Completing Survey: Arena Enhancement System");
addRedCoin("CANNONBALL56",200,"Completing Survey: Arena Enhancement System");
addRedCoin("reedc1",200,"Completing Survey: Arena Enhancement System");
addRedCoin("Fleet_Feet",200,"Completing Survey: Arena Enhancement System");
addRedCoin("KingKenzo",200,"Completing Survey: Arena Enhancement System");
addRedCoin("rankored",200,"Completing Survey: Arena Enhancement System");
addRedCoin("Zerryie",200,"Completing Survey: Arena Enhancement System");
addRedCoin("XRRRX7331",200,"Completing Survey: Arena Enhancement System");
addRedCoin("sirmaiden",200,"Completing Survey: Arena Enhancement System");
addRedCoin("Picklebreath",200,"Completing Survey: Arena Enhancement System");
addRedCoin("Schivnorr",200,"Completing Survey: Arena Enhancement System");
addRedCoin("sorrydie10",200,"Completing Survey: Arena Enhancement System");
addRedCoin("celo747",200,"Completing Survey: Arena Enhancement System");
addRedCoin("Sabin7",200,"Completing Survey: Arena Enhancement System");
addRedCoin("XxCradx",200,"Completing Survey: Arena Enhancement System");
addRedCoin("Killerkarnickel",200,"Completing Survey: Arena Enhancement System");
addRedCoin("noobguy123456789",200,"Completing Survey: Arena Enhancement System");
addRedCoin("indy5000",200,"Completing Survey: Arena Enhancement System");
addRedCoin("as820802",200,"Completing Survey: Arena Enhancement System");
addRedCoin("iamnoone",200,"Completing Survey: Arena Enhancement System");
addRedCoin("gregjo",200,"Completing Survey: Arena Enhancement System");
addRedCoin("calvinjliao",200,"Completing Survey: Arena Enhancement System");
addRedCoin("sammy_dude10",200,"Completing Survey: Arena Enhancement System");
addRedCoin("Kotose",200,"Completing Survey: Arena Enhancement System");
addRedCoin("Backernater",200,"Completing Survey: Arena Enhancement System");
addRedCoin("Hua9801",200,"Completing Survey: Arena Enhancement System");
addRedCoin("DarkJak92",200,"Completing Survey: Arena Enhancement System");
addRedCoin("PbookR",200,"Completing Survey: Arena Enhancement System");
addRedCoin("Bowshewicz",200,"Completing Survey: Arena Enhancement System");
addRedCoin("jjw17",200,"Completing Survey: Arena Enhancement System");
addRedCoin("7smartone7",200,"Completing Survey: Arena Enhancement System");
addRedCoin("ElijahBeaudoin",200,"Completing Survey: Arena Enhancement System");
addRedCoin("ArcticTrident",200,"Completing Survey: Arena Enhancement System");
addRedCoin("Squigglet",200,"Completing Survey: Arena Enhancement System");
addRedCoin("Apathist",200,"Completing Survey: Arena Enhancement System");
addRedCoin("killaofgames280",200,"Completing Survey: Arena Enhancement System");
addRedCoin("tobykatt",200,"Completing Survey: Arena Enhancement System");
addRedCoin("mattl99",200,"Completing Survey: Arena Enhancement System");
addRedCoin("TheLostSoul622",200,"Completing Survey: Arena Enhancement System");
addRedCoin("accordingleaf",200,"Completing Survey: Arena Enhancement System");
addRedCoin("middaystars",200,"Completing Survey: Arena Enhancement System");
addRedCoin("redtom7",200,"Completing Survey: Arena Enhancement System");
addRedCoin("EsotericaVirtue",200,"Completing Survey: Arena Enhancement System");
addRedCoin("panikingdisco",200,"Completing Survey: Arena Enhancement System");
addRedCoin("Randomthought31",200,"Completing Survey: Arena Enhancement System");
addRedCoin("Thystonius",200,"Completing Survey: Arena Enhancement System");
addRedCoin("baloonatic",200,"Completing Survey: Arena Enhancement System");
addRedCoin("Woon1957",200,"Completing Survey: Arena Enhancement System");
addRedCoin("Gems",200,"Completing Survey: Arena Enhancement System");
addRedCoin("toshikitsy",200,"Completing Survey: Arena Enhancement System");
addRedCoin("civilde",200,"Completing Survey: Arena Enhancement System");
addRedCoin("PersonOfInterest",200,"Completing Survey: Arena Enhancement System");
addRedCoin("frae2",200,"Completing Survey: Arena Enhancement System");
addRedCoin("bobertlyer",200,"Completing Survey: Arena Enhancement System");
addRedCoin("wpolly",500,"[Test Version] Bug Report: Pre-explosion Armors are all hats");
addRedCoin("wpolly",500,"[Test Version] Bug Report: Gambler’s box display error");
addRedCoin("zieger",500,"[Test Version] Bug Report: Can’t add cards to FCG");
addRedCoin("wecl0me12",500,"[Test Version] Bug Report: Healing a zombie duck after it dies still damages it");
addRedCoin("peleg97",500,"[Test Version] Bug Report: Bonus rocks always work");
addRedCoin("peleg97",500,"[Test Version] Bug Report: In death match enemies are released from stun earlier than you");
addRedCoin("wpolly",500,"[Test Version] Bug Report: Title do not auto-upgrade");
addRedCoin("wpolly",500,"[Test Version] Bug Report: Data transfer broken");
addRedCoin("peleg97",500,"[Test Version] Bug Report: Epic skills show double cost");
addRedCoin("Psycroth",500,"[Test Version] Bug Report: Rewards listed in Bestiary");
addRedCoin("Arcanmster",500,"[Test Version] Bug Report: Savefile transfer system freezes midway");
addRedCoin("Zox457",500,"[Test Version] Bug Report: Garden – Wrong expire time");
addRedCoin("rcktzr",500,"[Test Version] Bug Report: The quality settings all make it low quality.");
addRedCoin("Aurian",500,"[Test Version] Bug Report: Max Boosts not decreasing properly");
addRedCoin("Aurian",500,"[Test Version] Bug Report: No way to remove bestiary bonus msg in breaking news");
addRedCoin("wpolly",500,"[Test Version] Bug Report: No Adventurer’s Trophy");
addRedCoin("Arcanmster",500,"[Test Version] Bug Report: Cannot attack with mouse in BA (Linux)");
addRedCoin("gregjo",500,"[Test Version] Bug Report: Mystery Shop Scrolling");
addRedCoin("UpsetFisherMAN",500,"[Test Version] Bug Report: Cannot purchase ranged weapons");
addRedCoin("Slain087",500,"[Test Version] Bug Report: Auto-Harvest card does not work");
addRedCoin("RyGuy5357",500,"[Test Version] Bug Report: bug report bug");
addRedCoin("wpolly",500,"[Test Version] Bug Report: Monster doesn’t spawn after finishing the Pyramid Battle");
addRedCoin("Majildian",500,"[Test Version] Bug Report: Quick Attack ignores weapon range");
addRedCoin("mariomaster5",500,"[Test Version] Bug Report: Teleporting stadium charecters?");
addRedCoin("ShadyKnight",500,"[Test Version] Bug Report: Cannnot exit Dark Pyramid");
addRedCoin("Aurian",500,"[Test Version] Bug Report: Dark Portal kill achievement");
addRedCoin("peleg97",500,"[Test Version] Bug Report: Minor breaking news bug");
addRedCoin("destroyer57345",500,"[Test Version] Bug Report: No warning for 9001 pathz.");
addRedCoin("Worst_master",500,"[Test Version] Bug Report: Spelling when getting a reward from dragon");
addRedCoin("RyGuy5357",500,"[Test Version] Bug Report: Switching weapons");
addRedCoin("Worst_master",500,"[Test Version] Bug Report: Blood Claw special");
addRedCoin("firecat6666",500,"[Test Version] Bug Report: “tukkun fcg champion” quest bugged, also ant spray");
addRedCoin("Aurian",500,"[Test Version] Bug Report: Rickroll’d does not transfer");
addRedCoin("Aurian",500,"[Test Version] Bug Report: Achievement tracking that doesn’t transfer");
addRedCoin("missingno",500,"[Test Version] Bug Report: Nonworking armor bonus adder");
addRedCoin("jerenator",500,"[Test Version] Bug Report: Min. boosts half price");
addRedCoin("Oddity",500,"[Test Version] Bug Report: Pong: Extreme Wind expiring at wrong time causes slow ball");
addRedCoin("Worst_master",500,"[Test Version] Bug Report: Enhancing like crazy");
addRedCoin("wpolly",500,"[Test Version] Bug Report: Dark portal kill achievement error");
addRedCoin("gregjo",500,"[Test Version] Bug Report: Cheater Achievement Reporting");
addRedCoin("Worst_master",500,"[Test Version] Bug Report: Breaking News, pixelated box");
addRedCoin("Worst_master",500,"[Test Version] Bug Report: Two Lolmarket master?");
addRedCoin("dingetje50",500,"[Test Version] Bug Report: Consecutive day bonus");
addRedCoin("Arcanmster",500,"[Test Version] Bug Report: FCG remaining cards counter goes negative");
addRedCoin("gregjo",500,"[Test Version] Bug Report: Boost Depletion Speed In Breaking News");
addRedCoin("duudez",500,"[Test Version] Bug Report: Movement of bombs");
addRedCoin("duudez",500,"[Test Version] Bug Report: Prehistoric mission");
addRedCoin("peleg97",500,"[Test Version] Bug Report: Stadium item fight wins on impossible aceivement not reporting");
addRedCoin("peleg97",500,"[Test Version] Bug Report: Tutorial Typing Error");
addRedCoin("tenco1",500,"[Test Version] Bug Report: Minor detail bug");
addRedCoin("tenco1",500,"[Test Version] Bug Report: (Another) minor detail bug");
addRedCoin("Glooble",500,"[Test Version] Bug Report: Cannot equip/unequip items");
addRedCoin("ThinkInvisible",500,"[Test Version] Bug Report: Careers button not working");
addRedCoin("Krazycarn",500,"[Test Version] Bug Report: Unable to Switch Equipment During Combat… without Combat!");
addRedCoin("Arcanmster",500,"[Test Version] Bug Report: Prehistoric time counter bug");
addRedCoin("morfinista",500,"[Test Version] Bug Report: BA: gear changing bug");
addRedCoin("Uauf3000",500,"[Test Version] Bug Report: TukkunFCG “???” Does not give cards");
addRedCoin("gregjo",500,"[Test Version] Bug Report: Can’t get out of Special Arena Mob Mission");
addRedCoin("gergjo",500,"[Test Version] Bug Report: BA Skill Reset Pixel Penalty");
addRedCoin("wpolly",500,"[Test Version] Bug Report: Souvenir transfer error");
addRedCoin("Worst_master",500,"[Test Version] Bug Report: Prehistoric Mision (I haven’t typed it wrong, you typed it.)");
addRedCoin("Worst_master",500,"[Test Version] Bug Report: Negative time? In awesome adventure.");
addRedCoin("Worst_master",500,"[Test Version] Bug Report: Sudden Death in Secret Lab?");
addRedCoin("Arcanmster",500,"[Test Version] Bug Report: Defend the generator mission / Secret lab DoT");
addRedCoin("Bluji",500,"[Test Version] Bug Report: ‘Crafting’ quest doesn’t work");
addRedCoin("Sephirothfan",500,"[Test Version] Bug Report: Tukkun FCG Deck Out?");
addRedCoin("duudez",500,"[Test Version] Bug Report: Cannot enter defend mission");
addRedCoin("duudez",500,"[Test Version] Bug Report: Pixle throw skill");
addRedCoin("gregjo",500,"[Test Version] Bug Report: Combo Breaking out of Pyramid");
addRedCoin("duudez",500,"[Test Version] Bug Report: RHK not working properly");
addRedCoin("Aurian",500,"[Test Version] Bug Report: Spraying ants by clicking on number doesn’t count for achievement");
addRedCoin("duudez",500,"[Test Version] Bug Report: Careres and enhancing");
addRedCoin("Aurian",500,"[Test Version] Bug Report: Adventure energy timer bug");
addRedCoin("Worst_master",500,"[Test Version] Bug Report: Rofltrainer’s Secret?");
addRedCoin("peleg97",500,"[Test Version] Bug Report: Weaken, poison, blind and maybe stun skills bug");
addRedCoin("Arcanmster",500,"[Test Version] Bug Report: [Arena] Att/Def/HP/MP upgrade with pixels (minor)");
addRedCoin("scarymania",500,"[Test Version] Bug Report: prehistoric mission bug");
addRedCoin("wecl0me12",500,"[Test Version] Bug Report: secret lab kills me instantly");
addRedCoin("UnlimitedBlades",500,"[Test Version] Bug Report: Awesome Adventures Typo");
addRedCoin("Aurian",500,"[Test Version] Bug Report: Plot exp transfer incorrect");
addRedCoin("Worst_master",500,"[Test Version] Bug Report: Mutiple Premium Sprayer ");
addRedCoin("Sturmfeder",500,"[Test Version] Bug Report: Spelling Error in Options Menu");
addRedCoin("Sturmfeder",500,"[Test Version] Bug Report: Special Wand Attack Power");
addRedCoin("gentleben24",500,"[Test Version] Bug Report: Careers types give coins");
addRedCoin("YukaTakeuchiFan",500,"Bug Report: Om Nom Nom cost");
addRedCoin("qlordz",500,"Bug Report: No rings after version 1382");
addRedCoin("silverknite1",500,"Bug Report: Cannot purchase explosion crate");
addRedCoin("towerman100",500,"Bug Report: grinning colosus burning rope transfer");
addRedCoin("ChaosII7",1000,"Bug Report: RoflTrainer’s Secret reward bug");
addRedCoin("Thomadin",1000,"Bug Report: Blue Coins -> Pixels with Burned Rope");
addRedCoin("wpolly",500,"Bug Report: FCG result screen bug");
addRedCoin("joel_d",1000,"Bug Report: Join Kongregate screen");
addRedCoin("Ryo_Sangnoir",500,"Bug Report: Bug sprayer lacks Breaking News");
addRedCoin("pinguin333",500,"Bug Report: Typing smiley island password costs pixels");
addRedCoin("qlordz",500,"Bug Report: Your item has been destroyed!undefined");
addRedCoin("Arcanmster",500,"Bug Report: Achievement progress tracker graphical bug");
addRedCoin("Sphoofle",500,"Bug Report: Added 1k Event Tokens Not Added");
addRedCoin("silverknite1",500,"Bug Report: Gambler’s Box Gives… Undefined?");
addRedCoin("Silencing",500,"Bug Report: Game Completion Time Displayed Incorrectly");
addRedCoin("Silencing",500,"Bug Report: Scores Not Being Sent");
addRedCoin("James1011R",500,"Bug Report: LOLMarket “both buy and sell values grayed out” Bug");
addRedCoin("etmoonshade",500,"Bug Report: Battle Arena Dark Mage Wand Incorrect Type");
addRedCoin("gregjo",500,"Bug Report: Title Editing (Minor)");
addRedCoin("SynthesisAlpha",1000,"Bug Report: Switching files alters garden tree values.");
addRedCoin("stingrayjayz",500,"Bug Report: Boxes quantity undefined.");
addRedCoin("jetz0r",500,"Bug Report: Not Getting Crafting EXP for every enchant.");
addRedCoin("Zakhep2",1000,"Bug Report: Safe hacking won’t work");
addRedCoin("pinguin333",500,"Bug Report: smiley island now sets mana to 1");
addRedCoin("Sturmfeder",500,"Bug Report: Buy/Sell All Information");
addRedCoin("Sonic303",500,"Bug Report: pyramid area glitch");
addRedCoin("DuncmanG",500,"Bug Report: LOLMarket Max Numbers don’t all update");
addRedCoin("ManaMiyavi",500,"Bug Report: Auto-Harvest card");
addRedCoin("YYZ133",500,"Bug Report: “MP Boost” Tier 4 skill incorrect description/effects");
addRedCoin("Isfan",500,"Bug Report: Idlebot & Autohide backfire");
addRedCoin("math_master",500,"Bug Report: Energy Charge is still white");
addRedCoin("UnlimitedBlades",1000,"Bug Report: Money Printer Level 27?");
addRedCoin("YYZ133",1000,"Bug Report: BA Post-explosion Special Wand “Power Attack” Skill Bug");
addRedCoin("rockstip",500,"Bug Report: Adventuring Energy Loss");
addRedCoin("wecl0me12",500,"Bug Report: Dying in prehistoric mission sometimes allows you to continue");
addRedCoin("halemaster",500,"Bug Report: Legendary Boxes at NaN");
addRedCoin("rockstip",500,"Bug Report: Hide Level, Exp, and Coins graphical bug");
addRedCoin("dariofg",500,"Bug Report: Bug in “Too much lag!” screen");
addRedCoin("somethingggg",250,"Bug Report: Very poor grammar.");
addRedCoin("qlordz",250,"Bug Report: Push text off bottom of item description");
addRedCoin("Arch_Gremlin",500,"Bug Report: Mission kommander mission");
addRedCoin("Sturmfeder",500,"Bug Report: Quick Insta-Progress Buying");
addRedCoin("naruto070797",500,"Bug Report: Wrong gamblers box description");
addRedCoin("Mcflopidisss",500,"Bug Report: Version 1386 Relic");
addRedCoin("offsides",500,"Bug Report: After Buying a new plot, incorrect garden points for next plot shown");
addRedCoin("23skidoosh",500,"Bug Report: Pre-explosion Armour");
addRedCoin("peleg97",750,"Bug Report: Double exp gain for item maker career");
addRedCoin("ThinkInvisible",500,"Bug Report: TukkunFCG Level Fail");
addRedCoin("Oddity",500,"Bug Report: v1388: Hit indicators no longer appear in Death Match");
addRedCoin("math_master",500,"Bug Report: Safe Zone? That’s not the name anymore.");
addRedCoin("Pimgd",500,"Bug Report: Combo remains when death by lab suffocation");
addRedCoin("gregjo",500,"Bug Report: Double Exp For Item Making Career");
addRedCoin("eat911",500,"Bug Report: Stadium text bug");
addRedCoin("BewareOfElephant",500,"Bug Report: No hits in the BA");
addRedCoin("23skidoosh",3500,"Exploit report: Infinate Red Coins");
addRedCoin("Picklebreath",250,"Bug Report: Getting career exp twice in the stadium?");
addRedCoin("DuncmanG",250,"Bug Report: Graphical glitch in prehistoric mission");
addRedCoin("123x1111",2500,"Exploit report: Battle Arena and Tukkun FCG at the same time");
addRedCoin("Flamewarden",250,"Bug Report: Lingering tooltip");
addRedCoin("Arch_Gremlin",500,"Bug Report: EXP graph display");
addRedCoin("DarkArmadaStudio",250,"Bug Report: [Stadium] Fastest Race Leaderboards");
addRedCoin("qlordz",500,"Bug Report: Legendary hunter not changing");
addRedCoin("etmoonshade",500,"Bug Report: Windowshade Mode Graphical Bug");
addRedCoin("rockstip",500,"Bug Report: Battle Arena Item Graphical Bug");
addRedCoin("peleg97",500,"Bug Report: Dying in the final rooms in the prehistoric mission leads to the next");
addRedCoin("Motters",500,"Bug Report: No daily bonuses");
addRedCoin("tijntje_7",500,"Bug Report: Pyramid damage numbers");
addRedCoin("Qwertyuiopas",500,"Bug Report: Daily rewards: clicking a box twice");
addRedCoin("Mindtruster",500,"Bug Report: Daily Bonus Screen");
addRedCoin("DavidMadsen",500,"Bug Report: No Daily Bonus Screen");
addRedCoin("AleXinoS",250,"Bug Report: Dragon made a grammar mistake! (Not at the part where it was intended)");
addRedCoin("Slain087",500,"Bug Report: Battle Arena Dark Pyramid parse error");
addRedCoin("darkraiders",500,"Bug Report: Heal give some extra damage and extra combo");
addRedCoin("milleraus10",750,"Bug Report: New Daily Bonus Box");
addRedCoin("Ryo_Sangnoir",250,"Bug Report: Arcade medal hovers stay when pressing space");
addRedCoin("arcain",500,"Bug Report: Too many skill points");
addRedCoin("Mindtruster",750,"Bug Report: TukkunFCG – PROFIT!!!!!");
addRedCoin("Vitrebreaker",500,"Bug Report: Not dead in the prehistoric mission");
addRedCoin("Motters",500,"Bug Report: New crafting UI shows wrong percentage for bonus adders");
addRedCoin("Arcanmster",250,"Bug Report: Standby mode message is cut");
addRedCoin("Thomadin",500,"Bug Report: Display Bug -> Enchanting with Armor Attackspeed Stone");
addRedCoin("pinguin333",500,"Bug Report: crafting material used highscore");
addRedCoin("ohnonooh",750,"Bug report: Career cost activation wrongly charged");
addRedCoin("BanditEX",250,"Bug report: Arcade prize display error");
addRedCoin("DaMaster9000",250,"Bug report: Spray Ants pop-up glitch");
addRedCoin("notfromearth",500,"Bug report: blue coin rewards don’t add up correctely");
addRedCoin("math_master",250,"Bug report: Holding left mouse button may move description");
addRedCoin("BIGTIPPER",250,"Bug report: MegaBoss Lvls Vary");
addRedCoin("nickthemenace",250,"Bug report: Red coin refund rate display too low");
addRedCoin("ChaosII7",250,"Bug report: Status icons clinging");
addRedCoin("Tama_Yoshi",500,"Bug report: Career time left glitch");
addRedCoin("hyperhippy92",500,"Bug report: Career Time Depletion Bug");
addRedCoin("Quizer",500,"Bug report: Forcing draws in TukkunFCG when decked out also causes poisoning");
addRedCoin("DuncmanG",250,"Bug report: Ascend mouse-over Text Unclear");
addRedCoin("sabbut",500,"Bug report: Doom Wizard heals himself over his maximum health");
addRedCoin("SpudY2K",500,"Bug report: Flickering Battle Arena Mission Stats");
addRedCoin("sabbut",250,"Bug report: Enhancing some weapons");
addRedCoin("notfromearth",500,"Bug report: GC rewards from progress bar");
addRedCoin("Aurian",1500,"Exploit report: Permanent Elite Temp. Max Boost");
addRedCoin("ExSane",750,"Exploit report: Sword of Ascendant abusable in Tower of DOOOOOOM");
addRedCoin("Selgald",750,"Exploit report: Lvl up wont stop");
addRedCoin("RedSun383",500,"Bug report: The same arcade daily reward awarded twice at midnight");
addRedCoin("madnesss",500,"Bug report: Double poisoning in TukkunFCG");
addRedCoin("XxCradx",500,"Bug report: Stadium – Teleport Through Obstacles (Deathmatch)");
addRedCoin("redrocketwestie",500,"Bug report: Lost/Glitched Achievements?");
addRedCoin("ParaTheNoia",500,"Bug report: Weaken does not lower your damage in Secret Lab");
addRedCoin("ArcanMster",500,"Bug report: Negative drowning damage");
addRedCoin("wpolly",500,"Bug report: No “Spawn Rate” bonuses on weapons");
addRedCoin("notfromearth",500,"Bug report: combo count in battle arena");
addRedCoin("notfromearth",500,"Exploit report");
addRedCoin("Majildian",500,"Bug report: Strange Machine gives the wrong adventure");
addRedCoin("crazyphysicist",500,"Bug report: FCG: no Pet bonus");
addRedCoin("Maciejas42",500,"Bug report: A little typo in AA");
addRedCoin("ChaosII7",500,"Bug report: Dying instantly in the BA");
addRedCoin("talenramel",500,"Bug report: BA death while in Menu");
addRedCoin("stryph",500,"Bug report: Quests Tab Broken");
addRedCoin("helbrid",250,"Bug report: instant achievements");
addRedCoin("notfromearth",250,"Bug report: bestiary page 4 not available");
addRedCoin("eragonpotter",500,"Bug report: LoLMarket Screen");
addRedCoin("n0body123",500,"Bug report: First Battle Arena travel arrow in tutorial");
addRedCoin("trisk22",500,"Bug report: Pet lost its level");
addRedCoin("Ketchupyoshi",500,"Bug report: TukkunFCG pet bug");
addRedCoin("ChaosII7",6000,"Item Design");
addRedCoin("theyareclose",6000,"Item Design");
addRedCoin("UpsetFisherMAN",5250,"Item Design");
addRedCoin("olsfa",500,"Item Design");
addRedCoin("ManaMiyavi",4500,"Item Design");
addRedCoin("weslleyend",6500,"Item Design");
addRedCoin("cabbawargod",7000,"Item Design");
addRedCoin("blackcat2000",4750,"Item Design");
addRedCoin("lucksz",3750,"Item Design");
addRedCoin("blazez998",3750,"Item Design");
addRedCoin("theyareclose",3750,"Item Design");
addRedCoin("Khnum666",3750,"Item Design");
addRedCoin("ChaosII7",3750,"Item Design");
addRedCoin("Squigglet",6500,"Item Design");
addRedCoin("Chaldon",3750,"Item Design");
addRedCoin("endril",6000,"Item Design");
addRedCoin("takumi152",1000,"Item Design");
addRedCoin("RaceBandit",2000,"Item Design");
addRedCoin("hyperhippy92",1000,"Item Design");
addRedCoin("Pika2346",1500,"Item Design");
addRedCoin("Chokladkakan",4500,"Item Design");
addRedCoin("ipwnu1337",2000,"Item Design");
addRedCoin("Manjies",4500,"Item Design");
addRedCoin("Chokladkakan",1500,"Item Design");
addRedCoin("Randomthought31",1500,"Item Design");
addRedCoin("Harrs",1500,"Item Design");
addRedCoin("bulletbarrage",1500,"Item Design");
addRedCoin("Deilig",3750,"Item Design");
addRedCoin("Sphoofle",6500,"Item Design");
addRedCoin("Kalitrima",4000,"Item Design");
addRedCoin("Axecutioner64",750,"Item Design");
addRedCoin("Quizer",1500,"");
addRedCoin("Chatturgha",3000,"Item Design");
addRedCoin("LucidCrux",30000,"Item Design");
addRedCoin("LucidCrux",70000,"Item Design");
addRedCoin("LucidCrux",40000,"Item Design");
addRedCoin("LucidCrux",40000,"Item Design");
addRedCoin("shinki12345",30000,"Item Design");
addRedCoin("ChaosII7",110000,"Item Design");
addRedCoin("ManaMiyavi",3000,"Item Design");
addRedCoin("UpsetFisherMAN",6000,"Item Design");
addRedCoin("wecl0me12",300,"Dragon of Wisdom Speeches");
addRedCoin("Pharrit",300,"Dragon of Wisdom Speeches");
addRedCoin("arit3",600,"Dragon of Wisdom Speeches");
addRedCoin("Dudenator2",300,"Dragon of Wisdom Speeches");
addRedCoin("ChaosII7",2000,"Dragon of Wisdom Speeches");
addRedCoin("Beeshrine09",1000,"Dragon of Wisdom Speeches");
addRedCoin("GhoullyX",300,"Dragon of Wisdom Speeches");
addRedCoin("SvartRuskTroll",600,"Dragon of Wisdom Speeches");
addRedCoin("als02",300,"Dragon of Wisdom Speeches");
addRedCoin("Darkringer",2000,"Dragon of Wisdom Speeches");
addRedCoin("Cunari",1000,"Dragon of Wisdom Speeches");
addRedCoin("102938475621",600,"Dragon of Wisdom Speeches");
addRedCoin("AuburnAttack21",2000,"Dragon of Wisdom Speeches");
addRedCoin("Mr27",1000,"Dragon of Wisdom Speeches");
addRedCoin("poser2",600,"Dragon of Wisdom Speeches");
addRedCoin("ForceofLight",1000,"Dragon of Wisdom Speeches");
addRedCoin("ManaMiyavi",1000,"Dragon of Wisdom Speeches");
addRedCoin("silux",1500,"Dragon of Wisdom Speeches");
addRedCoin("wercooler",1000,"Dragon of Wisdom Speeches");
addRedCoin("jxm1985",300,"Dragon of Wisdom Speeches");
addRedCoin("TheNeRD14",300,"Dragon of Wisdom Speeches");
addRedCoin("billybobfred",2000,"Dragon of Wisdom Speeches");
addRedCoin("CAdamH",300,"Dragon of Wisdom Speeches");
addRedCoin("LunaticNeko",2000,"Dragon of Wisdom Speeches");
addRedCoin("toadvine",2000,"Area Design: Foodlandistan");
addRedCoin("toadvine",131700,"Item Design");
addRedCoin("AirSalad",20,"You win!");
addRedCoin("TheChaosNinja",2,"Fine, here\'s a Red Coin for you. Or maybe two.");
addRedCoin("Tukkun",100000,"Test");
addRedCoin("PlazmaBurst2",-999999,"PM Spamming");
